"use strict";
/// <Propriété>
/// -----------------------------------------------------------------------------------------------------
/// Société Enviromatic sarl (Copyright)
/// 11 rue du Hainaut
/// 78570 Andrésy
/// -----------------------------------------------------------------------------------------------------
/// Projet : e-Valorplast (logiciel de gestion d'activité)
/// Création : 23/10/2018
/// ----------------------------------------------------------------------------------------------------- 
///
Object.defineProperty(exports, "__esModule", { value: true });
exports.ComponentDropdownType = exports.SearchResultType = exports.SearchElementType = exports.InputFormComponentElementType = exports.DataType = exports.NonConformiteFichierType = exports.EnvCommandeFournisseurStatutName = exports.CommandeFournisseurStatut = exports.ContactAdresseProcess = exports.DataColumnName = exports.HabilitationQualite = exports.HabilitationModuleCollectivite = exports.HabilitationModuleCentreDeTri = exports.HabilitationAdministration = exports.HabilitationMessagerie = exports.HabilitationStatistique = exports.HabilitationAnnuaire = exports.HabilitationLogistique = exports.ActionName = exports.MenuName = exports.ModuleName = void 0;
//Module system names
var ModuleName;
(function (ModuleName) {
    ModuleName["Logistique"] = "Logistique";
    ModuleName["Annuaire"] = "Annuaire";
    ModuleName["Statistique"] = "Statistique";
    ModuleName["Messagerie"] = "Messagerie";
    ModuleName["Administration"] = "Administration";
    ModuleName["ModuleCentreDeTri"] = "ModuleCentreDeTri";
    ModuleName["ModuleCollectivite"] = "ModuleCollectivite";
    ModuleName["Qualite"] = "Qualite";
})(ModuleName = exports.ModuleName || (exports.ModuleName = {}));
//Menu system names
var MenuName;
(function (MenuName) {
    MenuName["AdministrationMenuAdresseType"] = "AdministrationMenuAdresseType";
    MenuName["AdministrationMenuCivilite"] = "AdministrationMenuCivilite";
    MenuName["AdministrationMenuClientApplication"] = "AdministrationMenuClientApplication";
    MenuName["AdministrationMenuDescriptionControle"] = "AdministrationMenuDescriptionControle";
    MenuName["AdministrationMenuDescriptionCVQ"] = "AdministrationMenuDescriptionCVQ";
    MenuName["AdministrationMenuDescriptionReception"] = "AdministrationMenuDescriptionReception";
    MenuName["AdministrationMenuEquipementier"] = "AdministrationMenuEquipementier";
    MenuName["AdministrationMenuFonction"] = "AdministrationMenuFonction";
    MenuName["AdministrationMenuFournisseurTO"] = "AdministrationMenuFournisseurTO";
    MenuName["AdministrationMenuMontantIncitationQualite"] = "AdministrationMenuMontantIncitationQualite";
    MenuName["AdministrationMenuMotifAnomalieChargement"] = "AdministrationMenuMotifAnomalieChargement";
    MenuName["AdministrationMenuMotifAnomalieClient"] = "AdministrationMenuMotifAnomalieClient";
    MenuName["AdministrationMenuMotifAnomalieTransporteur"] = "AdministrationMenuMotifAnomalieTransporteur";
    MenuName["AdministrationMenuMotifCamionIncomplet"] = "AdministrationMenuMotifCamionIncomplet";
    MenuName["AdministrationMenuNonConformiteDemandeClientType"] = "AdministrationMenuNonConformiteDemandeClientType";
    MenuName["AdministrationMenuNonConformiteFamille"] = "AdministrationMenuNonConformiteFamille";
    MenuName["AdministrationMenuNonConformiteNature"] = "AdministrationMenuNonConformiteNature";
    MenuName["AdministrationMenuNonConformiteReponseClientType"] = "AdministrationMenuNonConformiteReponseClientType";
    MenuName["AdministrationMenuNonConformiteReponseFournisseurType"] = "AdministrationMenuNonConformiteReponseFournisseurType";
    MenuName["AdministrationMenuProcess"] = "AdministrationMenuProcess";
    MenuName["AdministrationMenuStandard"] = "AdministrationMenuStandard";
    MenuName["AdministrationMenuUtilisateur"] = "AdministrationMenuUtilisateur";
    MenuName["AdministrationMenuSecurite"] = "AdministrationMenuSecurite";
    MenuName["AdministrationMenuService"] = "AdministrationMenuService";
    MenuName["AdministrationMenuTitre"] = "AdministrationMenuTitre";
    MenuName["AdministrationMenuUtilisateurInactif"] = "AdministrationMenuUtilisateurInactif";
    MenuName["AnnuaireMenuIncitationQualite"] = "AnnuaireMenuIncitationQualite";
    MenuName["AnnuaireMenuEmailNoteCreditCollectivite"] = "AnnuaireMenuEmailNoteCreditCollectivite";
    MenuName["AnnuaireMenuSuiviEnvois"] = "AnnuaireMenuSuiviEnvois";
    MenuName["AnnuaireMenuEntite"] = "AnnuaireMenuEntite";
    MenuName["LogistiqueMenuCommandeClient"] = "LogistiqueMenuCommandeClient";
    MenuName["LogistiqueMenuCommandeFournisseur"] = "LogistiqueMenuCommandeFournisseur";
    MenuName["LogistiqueMenuEtatCoutTransport"] = "LogistiqueMenuEtatCoutTransport";
    MenuName["LogistiqueMenuExportSAGE"] = "LogistiqueMenuExportSAGE";
    MenuName["LogistiqueMenuExtractionTransport"] = "LogistiqueMenuExtractionTransport";
    MenuName["LogistiqueMenuImporterTransport"] = "LogistiqueMenuImporterTransport";
    MenuName["LogistiqueMenuImpression"] = "LogistiqueMenuImpression";
    MenuName["LogistiqueMenuLotDisponible"] = "LogistiqueMenuLotDisponible";
    MenuName["LogistiqueMenuModifierTransport"] = "LogistiqueMenuModifierTransport";
    MenuName["LogistiqueMenuModifierTousPrixTransport"] = "LogistiqueMenuModifierTousPrixTransport";
    MenuName["LogistiqueMenuPrixReprise"] = "LogistiqueMenuPrixReprise";
    MenuName["LogistiqueMenuRepartition"] = "LogistiqueMenuRepartition";
    MenuName["LogistiqueMenuSupprimerTransportEnMasse"] = "LogistiqueMenuSupprimerTransportEnMasse";
    MenuName["LogistiqueMenuSurcoutCarburant"] = "LogistiqueMenuSurcoutCarburant";
    MenuName["LogistiqueMenuTransportDemandeEnlevement"] = "LogistiqueMenuTransportDemandeEnlevement";
    MenuName["LogistiqueMenuTransportCommande"] = "LogistiqueMenuTransportCommande";
    MenuName["LogistiqueMenuTransportCommandeEnCours"] = "LogistiqueMenuTransportCommandeEnCours";
    MenuName["LogistiqueMenuTransportCommandeModifiee"] = "LogistiqueMenuTransportCommandeModifiee";
    MenuName["LogistiqueMenuTransportNonValide"] = "LogistiqueMenuTransportNonValide";
    MenuName["LogistiqueMenuValiderNouveauPrixTransport"] = "LogistiqueMenuValiderNouveauPrixTransport";
    MenuName["LogistiqueMenuVisualisationAnnuaire"] = "LogistiqueMenuVisualisationAnnuaire";
    MenuName["LogistiqueMenuEtatReceptionEmballagePlastique"] = "LogistiqueMenuEtatReceptionEmballagePlastique";
    MenuName["LogistiqueMenuEtatSuiviTonnageRecycleur"] = "LogistiqueMenuEtatSuiviTonnageRecycleur";
    MenuName["LogistiqueMenuEtatDesFluxDev"] = "LogistiqueMenuEtatDesFluxDev";
    MenuName["LogistiqueMenuEtatTarifTransporteurClient"] = "LogistiqueMenuEtatTarifTransporteurClient";
    MenuName["LogistiqueMenuPartMarcheTransporteur"] = "LogistiqueMenuPartMarcheTransporteur";
    MenuName["LogistiqueMenuEtatKmMoyen"] = "LogistiqueMenuEtatKmMoyen";
    MenuName["LogistiqueMenuSuiviCommandeClient"] = "LogistiqueMenuSuiviCommandeClient";
    MenuName["LogistiqueMenuSuiviCommandeClientProduit"] = "LogistiqueMenuSuiviCommandeClientProduit";
    MenuName["LogistiqueMenuEtatReceptionProduit"] = "LogistiqueMenuEtatReceptionProduit";
    MenuName["LogistiqueMenuEtatReceptionProduitDR"] = "LogistiqueMenuEtatReceptionProduitDR";
    MenuName["LogistiqueMenuExtractionReception"] = "LogistiqueMenuExtractionReception";
    MenuName["LogistiqueMenuExtractionCommande"] = "LogistiqueMenuExtractionCommande";
    MenuName["LogistiqueMenuEtatDesPoids"] = "LogistiqueMenuEtatDesPoids";
    MenuName["LogistiqueMenuEtatTonnageParProcess"] = "LogistiqueMenuEtatTonnageParProcess";
    MenuName["LogistiqueMenuEtatVenteAnnuelleProduitClient"] = "LogistiqueMenuEtatVenteAnnuelleProduitClient";
    MenuName["LogistiqueMenuEtatDestinationAnnuelleProduitClient"] = "LogistiqueMenuEtatDestinationAnnuelleProduitClient";
    MenuName["LogistiqueMenuSuiviFacturationHC"] = "LogistiqueMenuSuiviFacturationHC";
    MenuName["LogistiqueMenuTonnageCollectiviteProduit"] = "LogistiqueMenuTonnageCollectiviteProduit";
    MenuName["LogistiqueMenuTonnageCDTProduitComposant"] = "LogistiqueMenuTonnageCDTProduitComposant";
    MenuName["LogistiqueMenuTonnageCLSousContrat"] = "LogistiqueMenuTonnageCLSousContrat";
    MenuName["LogistiqueMenuListeProduit"] = "LogistiqueMenuListeProduit";
    MenuName["MessagerieMenuMessage"] = "MessagerieMenuMessage";
    MenuName["MessagerieMenuVisualisation"] = "MessagerieMenuVisualisation";
    MenuName["QualiteMenuControle"] = "QualiteMenuControle";
    MenuName["QualiteMenuNonConformite"] = "QualiteMenuNonConformite";
    MenuName["QualiteMenuRepartitionControleClient"] = "QualiteMenuRepartitionControleClient";
    MenuName["QualiteMenuExtractionFicheControle"] = "QualiteMenuExtractionFicheControle";
    MenuName["QualiteMenuExtractionControle"] = "QualiteMenuExtractionControle";
    MenuName["QualiteMenuExtractionNonConformite"] = "QualiteMenuExtractionNonConformite";
    MenuName["QualiteMenuExtractionCVQ"] = "QualiteMenuExtractionCVQ";
    MenuName["QualiteMenuEtatIncitationQualite"] = "QualiteMenuEtatIncitationQualite";
    MenuName["QualiteMenuEtatControleReception"] = "QualiteMenuEtatControleReception";
})(MenuName = exports.MenuName || (exports.MenuName = {}));
//Actions system names
var ActionName;
(function (ActionName) {
    ActionName["ValidateTransportPrice"] = "ValidateTransportPrice";
    ActionName["RejectTransportPrice"] = "RejectTransportPrice";
    ActionName["DeleteTransport"] = "DeleteTransport";
    ActionName["SetEnAttente"] = "SetEnAttente";
    ActionName["ChangeMoisDechargementPrevu"] = "ChangeMoisDechargementPrevu";
    ActionName["CopyPrixReprise"] = "CopyPrixReprise";
    ActionName["CentreDeTriForUtilisateur"] = "CentreDeTriForUtilisateur";
    ActionName["DeactivateUtilisateur"] = "DeactivateUtilisateur";
})(ActionName = exports.ActionName || (exports.ActionName = {}));
//Habilitations Module logistique
var HabilitationLogistique;
(function (HabilitationLogistique) {
    HabilitationLogistique["Administrateur"] = "Administrateur";
    HabilitationLogistique["Transporteur"] = "Transporteur";
    HabilitationLogistique["Client"] = "Client";
    HabilitationLogistique["Utilisateur"] = "Utilisateur";
    HabilitationLogistique["CentreDeTri"] = "CentreDeTri";
})(HabilitationLogistique = exports.HabilitationLogistique || (exports.HabilitationLogistique = {}));
//Habilitations de l"annuaire
var HabilitationAnnuaire;
(function (HabilitationAnnuaire) {
    HabilitationAnnuaire["Administrateur"] = "Administrateur";
    HabilitationAnnuaire["ADV"] = "ADV";
    HabilitationAnnuaire["DR"] = "DR";
    HabilitationAnnuaire["Logistique"] = "Logistique";
    HabilitationAnnuaire["Qualite"] = "Qualite";
    HabilitationAnnuaire["Visualisation"] = "Visualisation";
})(HabilitationAnnuaire = exports.HabilitationAnnuaire || (exports.HabilitationAnnuaire = {}));
//Habilitations Module statistiques
var HabilitationStatistique;
(function (HabilitationStatistique) {
    HabilitationStatistique["Utilisateur"] = "Utilisateur";
})(HabilitationStatistique = exports.HabilitationStatistique || (exports.HabilitationStatistique = {}));
//Habilitations Module messagerie
var HabilitationMessagerie;
(function (HabilitationMessagerie) {
    HabilitationMessagerie["Administrateur"] = "Administrateur";
    HabilitationMessagerie["Utilisateur"] = "Utilisateur";
})(HabilitationMessagerie = exports.HabilitationMessagerie || (exports.HabilitationMessagerie = {}));
//Habilitations Module administration
var HabilitationAdministration;
(function (HabilitationAdministration) {
    HabilitationAdministration["Administrateur"] = "Administrateur";
})(HabilitationAdministration = exports.HabilitationAdministration || (exports.HabilitationAdministration = {}));
//Habilitations Module centre de tri
var HabilitationModuleCentreDeTri;
(function (HabilitationModuleCentreDeTri) {
    HabilitationModuleCentreDeTri["Administrateur"] = "Administrateur";
    HabilitationModuleCentreDeTri["Utilisateur"] = "Utilisateur";
})(HabilitationModuleCentreDeTri = exports.HabilitationModuleCentreDeTri || (exports.HabilitationModuleCentreDeTri = {}));
//Habilitations module collectivité
var HabilitationModuleCollectivite;
(function (HabilitationModuleCollectivite) {
    HabilitationModuleCollectivite["Administrateur"] = "Administrateur";
    HabilitationModuleCollectivite["Utilisateur"] = "Utilisateur";
})(HabilitationModuleCollectivite = exports.HabilitationModuleCollectivite || (exports.HabilitationModuleCollectivite = {}));
//Habilitations Module qualité
var HabilitationQualite;
(function (HabilitationQualite) {
    HabilitationQualite["Administrateur"] = "Administrateur";
    HabilitationQualite["Client"] = "Client";
    HabilitationQualite["Utilisateur"] = "Utilisateur";
    HabilitationQualite["Fournisseur"] = "Fournisseur";
})(HabilitationQualite = exports.HabilitationQualite || (exports.HabilitationQualite = {}));
//Enumération pour les noms de colonne
var DataColumnName;
(function (DataColumnName) {
    DataColumnName["Adresse"] = "Adresse";
    DataColumnName["TexteAdresseList"] = "TexteAdresseList";
    DataColumnName["AdresseDestinationCP"] = "AdresseDestinationCP";
    DataColumnName["AdresseDestinationDpt"] = "AdresseDestinationDpt";
    DataColumnName["AdresseDestinationTypeLibelle"] = "AdresseDestinationTypeLibelle";
    DataColumnName["AdresseDestinationVille"] = "AdresseDestinationVille";
    DataColumnName["AdresseOrigineCP"] = "AdresseOrigineCP";
    DataColumnName["AdresseOrigineTypeLibelle"] = "AdresseOrigineTypeLibelle";
    DataColumnName["AdresseOrigineVille"] = "AdresseOrigineVille";
    DataColumnName["Annee"] = "Annee";
    DataColumnName["AnneeNb"] = "AnneeNb";
    DataColumnName["ApplicationProduitOrigineLibelle"] = "ApplicationProduitOrigineLibelle";
    DataColumnName["CamionTypeLibelle"] = "CamionTypeLibelle";
    DataColumnName["CentreDeTriLibelle"] = "CentreDeTriLibelle";
    DataColumnName["CiviliteLibelle"] = "CiviliteLibelle";
    DataColumnName["ClientLibelle"] = "ClientLibelle";
    DataColumnName["CommandeClientMensuelleD"] = "CommandeClientMensuelleD";
    DataColumnName["CommandeClientMensuellePoids"] = "CommandeClientMensuellePoids";
    DataColumnName["CommandeClientPositionne"] = "CommandeClientPositionne";
    DataColumnName["CommandeFournisseurAdresseOrigineDpt"] = "CommandeFournisseurAdresseOrigineDpt";
    DataColumnName["CommandeFournisseurAdresseOrigineVille"] = "CommandeFournisseurAdresseOrigineVille";
    DataColumnName["CommandeFournisseurCamionComplet"] = "CommandeFournisseurCamionComplet";
    DataColumnName["CommandeFournisseurCamionCompletInvisible"] = "CommandeFournisseurCamionCompletInvisible";
    DataColumnName["CommandeFournisseurCB"] = "CommandeFournisseurCB";
    DataColumnName["CommandeFournisseurCVQ"] = "CommandeFournisseurCVQ";
    DataColumnName["CommandeFournisseurDAffretement"] = "CommandeFournisseurDAffretement";
    DataColumnName["CommandeFournisseurDateCreation"] = "CommandeFournisseurDateCreation";
    DataColumnName["CommandeFournisseurDChargement"] = "CommandeFournisseurDChargement";
    DataColumnName["CommandeFournisseurDChargementPrevue"] = "CommandeFournisseurDChargementPrevue";
    DataColumnName["CommandeFournisseurDDechargement"] = "CommandeFournisseurDDechargement";
    DataColumnName["CommandeFournisseurDDechargementInvisible"] = "CommandeFournisseurDDechargementInvisible";
    DataColumnName["CommandeFournisseurDDechargementPrevue"] = "CommandeFournisseurDDechargementPrevue";
    DataColumnName["CommandeFournisseurDDisponibilite"] = "CommandeFournisseurDDisponibilite";
    DataColumnName["CommandeFournisseurDTraitementAnomalieChargement"] = "CommandeFournisseurDTraitementAnomalieChargement";
    DataColumnName["CommandeFournisseurDTraitementAnomalieClient"] = "CommandeFournisseurDTraitementAnomalieClient";
    DataColumnName["CommandeFournisseurDTraitementAnomalieTransporteur"] = "CommandeFournisseurDTraitementAnomalieTransporteur";
    DataColumnName["CommandeFournisseurFicheControle"] = "CommandeFournisseurFicheControle";
    DataColumnName["CommandeFournisseurHoraireDechargementPrevu"] = "CommandeFournisseurHoraireDechargementPrevu";
    DataColumnName["CommandeFournisseurImprime"] = "CommandeFournisseurImprime";
    DataColumnName["CommandeFournisseurKm"] = "CommandeFournisseurKm";
    DataColumnName["CommandeFournisseurLimiteExclusivite"] = "CommandeFournisseurLimiteExclusivite";
    DataColumnName["CommandeFournisseurMixte"] = "CommandeFournisseurMixte";
    DataColumnName["CommandeFournisseurMoisDechargementPrevu"] = "CommandeFournisseurMoisDechargementPrevu";
    DataColumnName["CommandeFournisseurNbBalleChargement"] = "CommandeFournisseurNbBalleChargement";
    DataColumnName["CommandeFournisseurNbBalleDechargement"] = "CommandeFournisseurNbBalleDechargement";
    DataColumnName["CommandeFournisseurNumeroCommande"] = "CommandeFournisseurNumeroCommande";
    DataColumnName["CommandeFournisseurNumeroAffretement"] = "CommandeFournisseurNumeroAffretement";
    DataColumnName["CommandeFournisseurPoidsChargement"] = "CommandeFournisseurPoidsChargement";
    DataColumnName["CommandeFournisseurPoidsDechargement"] = "CommandeFournisseurPoidsDechargement";
    DataColumnName["CommandeFournisseurPoidsReparti"] = "CommandeFournisseurPoidsReparti";
    DataColumnName["CommandeFournisseurPrixTransportHT"] = "CommandeFournisseurPrixTransportHT";
    DataColumnName["CommandeFournisseurPrixTransportSupplementHT"] = "CommandeFournisseurPrixTransportSupplementHT";
    DataColumnName["CommandeFournisseurStatut"] = "CommandeFournisseurStatut";
    DataColumnName["CommandeFournisseurPrixTonneHT"] = "CommandeFournisseurPrixTonneHT";
    DataColumnName["CommandeFournisseurSurcoutCarburantHT"] = "CommandeFournisseurSurcoutCarburantHT";
    DataColumnName["CommandeFournisseurNonConformite"] = "CommandeFournisseurNonConformite";
    DataColumnName["CommandeFournisseurNonConformiteInvisible"] = "CommandeFournisseurNonConformiteInvisible";
    DataColumnName["CommandeFournisseurNbTotalLivraison"] = "CommandeFournisseurNbTotalLivraison";
    DataColumnName["CommandeFournisseurNbTotalLivraisonAControler"] = "CommandeFournisseurNbTotalLivraisonAControler";
    DataColumnName["CommandeFournisseurNbTotalLivraisonControlees"] = "CommandeFournisseurNbTotalLivraisonControlees";
    DataColumnName["CommandeFournisseurTauxControle"] = "CommandeFournisseurTauxControle";
    DataColumnName["ComposantLibelle"] = "ComposantLibelle";
    DataColumnName["CollectiviteLibelle"] = "CollectiviteLibelle";
    DataColumnName["ContactAdresseEmail"] = "ContactAdresseEmail";
    DataColumnName["ControleCmt"] = "ControleCmt";
    DataColumnName["ControleDControle"] = "ControleDControle";
    DataColumnName["ControlePoids"] = "ControlePoids";
    DataColumnName["ControlePoidsTotal"] = "ControlePoidsTotal";
    DataColumnName["ControlePoidsTotalIndesirable"] = "ControlePoidsTotalIndesirable";
    DataColumnName["ControlePourcentageIndesirable"] = "ControlePourcentageIndesirable";
    DataColumnName["Controles"] = "Controles";
    DataColumnName["CVQCmt"] = "CVQCmt";
    DataColumnName["CVQDCVQ"] = "CVQDCVQ";
    DataColumnName["DescriptionControleActif"] = "DescriptionControleActif";
    DataColumnName["DescriptionControleCalculLimiteConformite"] = "DescriptionControleCalculLimiteConformite";
    DataColumnName["DescriptionControleLibelleFRFR"] = "DescriptionControleLibelleFRFR";
    DataColumnName["DescriptionControleLibelleENGB"] = "DescriptionControleLibelleENGB";
    DataColumnName["DescriptionControleOrdre"] = "DescriptionControleOrdre";
    DataColumnName["DescriptionCVQActif"] = "DescriptionCVQActif";
    DataColumnName["DescriptionCVQLibelleFRFR"] = "DescriptionCVQLibelleFRFR";
    DataColumnName["DescriptionCVQLibelleENGB"] = "DescriptionCVQLibelleENGB";
    DataColumnName["DescriptionCVQLimiteBasse"] = "DescriptionCVQLimiteBasse";
    DataColumnName["DescriptionCVQLimiteHaute"] = "DescriptionCVQLimiteHaute";
    DataColumnName["DescriptionCVQOrdre"] = "DescriptionCVQOrdre";
    DataColumnName["DescriptionReceptionActif"] = "DescriptionReceptionActif";
    DataColumnName["DescriptionReceptionLibelleFRFR"] = "DescriptionReceptionLibelleFRFR";
    DataColumnName["DescriptionReceptionLibelleENGB"] = "DescriptionReceptionLibelleENGB";
    DataColumnName["DescriptionReceptionOuiFRFR"] = "DescriptionReceptionOuiFRFR";
    DataColumnName["DescriptionReceptionOuiENGB"] = "DescriptionReceptionOuiENGB";
    DataColumnName["DescriptionReceptionNonFRFR"] = "DescriptionReceptionNonFRFR";
    DataColumnName["DescriptionReceptionNonENGB"] = "DescriptionReceptionNonENGB";
    DataColumnName["DescriptionReceptionOrdre"] = "DescriptionReceptionOrdre";
    DataColumnName["D"] = "D";
    DataColumnName["EmailDEnvoi"] = "EmailDEnvoi";
    DataColumnName["EntiteLibelle"] = "EntiteLibelle";
    DataColumnName["EntiteSousContrat"] = "EntiteSousContrat";
    DataColumnName["EntiteActif"] = "EntiteActif";
    DataColumnName["EntiteAdelphe"] = "EntiteAdelphe";
    DataColumnName["EntiteTypeLibelle"] = "EntiteTypeLibelle";
    DataColumnName["EntiteCodeCITEO"] = "EntiteCodeCITEO";
    DataColumnName["EquipementierLibelle"] = "EquipementierLibelle";
    DataColumnName["FicheControleControle"] = "FicheControleControle";
    DataColumnName["FicheControleCVQ"] = "FicheControleCVQ";
    DataColumnName["FicheControleReception"] = "FicheControleReception";
    DataColumnName["FicheControleNumeroLotUsine"] = "FicheControleNumeroLotUsine";
    DataColumnName["FicheControleReserve"] = "FicheControleReserve";
    DataColumnName["FicheControleCmt"] = "FicheControleCmt";
    DataColumnName["FicheControleControleur"] = "FicheControleControleur";
    DataColumnName["FonctionLibelle"] = "FonctionLibelle";
    DataColumnName["FournisseurLibelle"] = "FournisseurLibelle";
    DataColumnName["FournisseurTOLibelle"] = "FournisseurTOLibelle";
    DataColumnName["ListeDR"] = "ListeDR";
    DataColumnName["MessageLibelle"] = "MessageLibelle";
    DataColumnName["MessageDDebut"] = "MessageDDebut";
    DataColumnName["MessageDFin"] = "MessageDFin";
    DataColumnName["MessageTitre"] = "MessageTitre";
    DataColumnName["MessageTypeLibelle"] = "MessageTypeLibelle";
    DataColumnName["MessageVisualisationD"] = "MessageVisualisationD";
    DataColumnName["MessageVisualisationConfirme"] = "MessageVisualisationConfirme";
    DataColumnName["MessageVisualisationPar"] = "MessageVisualisationPar";
    DataColumnName["Montant"] = "Montant";
    DataColumnName["MotifAnomalieChargementLibelle"] = "MotifAnomalieChargementLibelle";
    DataColumnName["MotifAnomalieClientLibelle"] = "MotifAnomalieClientLibelle";
    DataColumnName["MotifAnomalieTransporteurLibelle"] = "MotifAnomalieTransporteurLibelle";
    DataColumnName["MotifCamionIncompletLibelle"] = "MotifCamionIncompletLibelle";
    DataColumnName["Nb"] = "Nb";
    DataColumnName["NonConformiteDateCreation"] = "NonConformiteDateCreation";
    DataColumnName["NonConformiteDescrClient"] = "NonConformiteDescrClient";
    DataColumnName["NonConformiteDescrValorplast"] = "NonConformiteDescrValorplast";
    DataColumnName["NonConformiteIF"] = "NonConformiteIF";
    DataColumnName["NonConformiteIFClient"] = "NonConformiteIFClient";
    DataColumnName["NonConformiteIFFournisseur"] = "NonConformiteIFFournisseur";
    DataColumnName["NonConformiteIFClientCmtFacturation"] = "NonConformiteIFClientCmtFacturation";
    DataColumnName["NonConformiteIFClientDFacture"] = "NonConformiteIFClientDFacture";
    DataColumnName["NonConformiteIFClientFactureMontant"] = "NonConformiteIFClientFactureMontant";
    DataColumnName["NonConformiteIFClientFactureNro"] = "NonConformiteIFClientFactureNro";
    DataColumnName["NonConformiteIFFournisseurAttenteBonCommandeNro"] = "NonConformiteIFFournisseurAttenteBonCommandeNro";
    DataColumnName["NonConformiteIFFournisseurBonCommandeNro"] = "NonConformiteIFFournisseurBonCommandeNro";
    DataColumnName["NonConformiteIFFournisseurCmtFacturation"] = "NonConformiteIFFournisseurCmtFacturation";
    DataColumnName["NonConformiteIFFournisseurDeductionTonnage"] = "NonConformiteIFFournisseurDeductionTonnage";
    DataColumnName["NonConformiteIFFournisseurFactureMontant"] = "NonConformiteIFFournisseurFactureMontant";
    DataColumnName["NonConformiteIFFournisseurFactureNro"] = "NonConformiteIFFournisseurFactureNro";
    DataColumnName["NonConformiteIFFournisseurRetourLot"] = "NonConformiteIFFournisseurRetourLot";
    DataColumnName["NonConformiteIFFournisseurTransmissionFacturation"] = "NonConformiteIFFournisseurTransmissionFacturation";
    DataColumnName["NonConformiteListeFamille"] = "NonConformiteListeFamille";
    DataColumnName["NonConformiteOriginePlanActionSaisi"] = "NonConformiteOriginePlanActionSaisi";
    DataColumnName["NonConformitePlanAction"] = "NonConformitePlanAction";
    DataColumnName["NonConformitePlanActionNonConcerne"] = "NonConformitePlanActionNonConcerne";
    DataColumnName["NonConformitePriseEnCharge"] = "NonConformitePriseEnCharge";
    DataColumnName["NonConformiteMontantPriseEnCharge"] = "NonConformiteMontantPriseEnCharge";
    DataColumnName["NonConformiteIFFournisseurFacture"] = "NonConformiteIFFournisseurFacture";
    DataColumnName["NonConformiteActionDR"] = "NonConformiteActionDR";
    DataColumnName["NonConformiteDTransmissionFournisseur"] = "NonConformiteDTransmissionFournisseur";
    DataColumnName["NonConformiteCmtPriseEnCharge"] = "NonConformiteCmtPriseEnCharge";
    DataColumnName["NonConformiteCmtReponseFournisseur"] = "NonConformiteCmtReponseFournisseur";
    DataColumnName["NonConformiteCmtReponseClient"] = "NonConformiteCmtReponseClient";
    DataColumnName["NonConformiteEtapeDValide"] = "NonConformiteEtapeDValide";
    DataColumnName["NonConformiteEtapeLibelle"] = "NonConformiteEtapeLibelle";
    DataColumnName["NonConformiteCloturee"] = "NonConformiteCloturee";
    DataColumnName["NonConformiteClotureeInvisible"] = "NonConformiteClotureeInvisible";
    DataColumnName["NonConformiteDemandeClientTypeActif"] = "NonConformiteDemandeClientTypeActif";
    DataColumnName["NonConformiteDemandeClientTypeLibelle"] = "NonConformiteDemandeClientTypeLibelle";
    DataColumnName["NonConformiteDemandeClientTypeLibelleFRFR"] = "NonConformiteDemandeClientTypeLibelleFRFR";
    DataColumnName["NonConformiteDemandeClientTypeLibelleENGB"] = "NonConformiteDemandeClientTypeLibelleENGB";
    DataColumnName["NonConformiteAccordFournisseurTypeLibelle"] = "NonConformiteAccordFournisseurTypeLibelle";
    DataColumnName["NonConformiteFamilleActif"] = "NonConformiteFamilleActif";
    DataColumnName["NonConformiteFamilleIncitationQualite"] = "NonConformiteFamilleIncitationQualite";
    DataColumnName["NonConformiteFamilleLibelle"] = "NonConformiteFamilleLibelle";
    DataColumnName["NonConformiteFamilleLibelleFRFR"] = "NonConformiteFamilleLibelleFRFR";
    DataColumnName["NonConformiteFamilleLibelleENGB"] = "NonConformiteFamilleLibelleENGB";
    DataColumnName["NonConformiteNatureActif"] = "NonConformiteNatureActif";
    DataColumnName["NonConformiteNatureIncitationQualite"] = "NonConformiteNatureIncitationQualite";
    DataColumnName["NonConformiteNatureLibelle"] = "NonConformiteNatureLibelle";
    DataColumnName["NonConformiteNatureLibelleFRFR"] = "NonConformiteNatureLibelleFRFR";
    DataColumnName["NonConformiteNatureLibelleENGB"] = "NonConformiteNatureLibelleENGB";
    DataColumnName["NonConformiteReponseClientTypeActif"] = "NonConformiteReponseClientTypeActif";
    DataColumnName["NonConformiteReponseClientTypeLibelle"] = "NonConformiteReponseClientTypeLibelle";
    DataColumnName["NonConformiteReponseClientTypeLibelleFRFR"] = "NonConformiteReponseClientTypeLibelleFRFR";
    DataColumnName["NonConformiteReponseClientTypeLibelleENGB"] = "NonConformiteReponseClientTypeLibelleENGB";
    DataColumnName["NonConformiteReponseFournisseurTypeActif"] = "NonConformiteReponseFournisseurTypeActif";
    DataColumnName["NonConformiteReponseFournisseurTypeLibelle"] = "NonConformiteReponseFournisseurTypeLibelle";
    DataColumnName["NonConformiteReponseFournisseurTypeLibelleFRFR"] = "NonConformiteReponseFournisseurTypeLibelleFRFR";
    DataColumnName["NonConformiteReponseFournisseurTypeLibelleENGB"] = "NonConformiteReponseFournisseurTypeLibelleENGB";
    DataColumnName["ParcoursKm"] = "ParcoursKm";
    DataColumnName["PaysDestinbationLibelle"] = "PaysDestinbationLibelle";
    DataColumnName["PaysLibelle"] = "PaysLibelle";
    DataColumnName["PrixRepriseD"] = "PrixRepriseD";
    DataColumnName["PrixReprisePUHT"] = "PrixReprisePUHT";
    DataColumnName["PrixReprisePUHTSurtri"] = "PrixReprisePUHTSurtri";
    DataColumnName["PrixReprisePUHTTransport"] = "PrixReprisePUHTTransport";
    DataColumnName["ProcessLibelle"] = "ProcessLibelle";
    DataColumnName["ProduitLibelle"] = "ProduitLibelle";
    DataColumnName["ProduitActif"] = "ProduitActif";
    DataColumnName["ProduitNomCommercial"] = "ProduitNomCommercial";
    DataColumnName["ProduitNomCommun"] = "ProduitNomCommun";
    DataColumnName["ProduitNumeroStatistique"] = "ProduitNumeroStatistique";
    DataColumnName["ProduitCodeListeVerte"] = "ProduitCodeListeVerte";
    DataColumnName["ProduitCodeEE"] = "ProduitCodeEE";
    DataColumnName["ProduitCmt"] = "ProduitCmt";
    DataColumnName["ProduitPUHTSurtri"] = "ProduitPUHTSurtri";
    DataColumnName["ProduitPUHTTransport"] = "ProduitPUHTTransport";
    DataColumnName["ProduitGroupeReportingLibelle"] = "ProduitGroupeReportingLibelle";
    DataColumnName["ProduitGroupeReportingTypeLibelle"] = "ProduitGroupeReportingTypeLibelle";
    DataColumnName["RegionReportingLibelle"] = "RegionReportingLibelle";
    DataColumnName["SAGECodeTransportCode"] = "SAGECodeTransportCode";
    DataColumnName["SAGECodeTransportLibelle"] = "SAGECodeTransportLibelle";
    DataColumnName["SAGENumeroPiece"] = "SAGENumeroPiece";
    DataColumnName["SAGEDatePiece"] = "SAGEDatePiece";
    DataColumnName["ServiceLibelle"] = "ServiceLibelle";
    DataColumnName["StandardLibelle"] = "StandardLibelle";
    DataColumnName["TitreLibelle"] = "TitreLibelle";
    DataColumnName["UtilisateurActif"] = "UtilisateurActif";
    DataColumnName["UtilisateurNom"] = "UtilisateurNom";
    DataColumnName["UtilisateurLogin"] = "UtilisateurLogin";
    DataColumnName["UtilisateurHabilitationLogistique"] = "UtilisateurHabilitationLogistique";
    DataColumnName["UtilisateurHabilitationAnnuaire"] = "UtilisateurHabilitationAnnuaire";
    DataColumnName["UtilisateurHabilitationMessagerie"] = "UtilisateurHabilitationMessagerie";
    DataColumnName["UtilisateurHabilitationAdministration"] = "UtilisateurHabilitationAdministration";
    DataColumnName["UtilisateurHabilitationQualite"] = "UtilisateurHabilitationQualite";
    DataColumnName["UtilisateurClient"] = "UtilisateurClient";
    DataColumnName["UtilisateurHabilitationModuleTransporteur"] = "UtilisateurHabilitationModuleTransporteur";
    DataColumnName["UtilisateurTransporteur"] = "UtilisateurTransporteur";
    DataColumnName["UtilisateurHabilitationModuleCollectivite"] = "UtilisateurHabilitationModuleCollectivite";
    DataColumnName["UtilisateurCollectivite"] = "UtilisateurCollectivite";
    DataColumnName["UtilisateurHabilitationModuleCentreDeTri"] = "UtilisateurHabilitationModuleCentreDeTri";
    DataColumnName["UtilisateurCentreDeTri"] = "UtilisateurCentreDeTri";
    DataColumnName["Couleur"] = "Couleur";
    DataColumnName["Mois"] = "Mois";
    DataColumnName["MoisNb"] = "MoisNb";
    DataColumnName["MoisAnnee"] = "MoisAnnee";
    DataColumnName["TrimestreNb"] = "TrimestreNb";
    DataColumnName["Ordre"] = "Ordre";
    DataColumnName["TonnageTotalChargement"] = "TonnageTotalChargement";
    DataColumnName["TonnageTotalDeclare"] = "TonnageTotalDeclare";
    DataColumnName["TonnageMoyen"] = "TonnageMoyen";
    DataColumnName["NbTotalCamion"] = "NbTotalCamion";
    DataColumnName["TonnageSoumisInteressement"] = "TonnageSoumisInteressement";
    DataColumnName["NbLotSoumisInteressement"] = "NbLotSoumisInteressement";
    DataColumnName["NbLotNonConforme"] = "NbLotNonConforme";
    DataColumnName["TauxNonConformite"] = "TauxNonConformite";
    DataColumnName["MontantInteressement"] = "MontantInteressement";
    DataColumnName["SousContratAutocontrole"] = "SousContratAutocontrole";
    DataColumnName["MiseEnPlaceAutocontrole"] = "MiseEnPlaceAutocontrole";
    DataColumnName["TonnageSousContrat"] = "TonnageSousContrat";
    DataColumnName["NbAffretement"] = "NbAffretement";
    DataColumnName["NbAffretementPourcentage"] = "NbAffretementPourcentage";
    DataColumnName["NbCommandeFournisseur"] = "NbCommandeFournisseur";
    DataColumnName["CA"] = "CA";
    DataColumnName["CAPourcentage"] = "CAPourcentage";
    DataColumnName["PoidsDechargementTotal"] = "PoidsDechargementTotal";
    DataColumnName["PoidsDechargementAffretement"] = "PoidsDechargementAffretement";
    DataColumnName["KmAffretement"] = "KmAffretement";
    DataColumnName["KmTotal"] = "KmTotal";
    DataColumnName["PrixEuroHT"] = "PrixEuroHT";
    DataColumnName["PrixEuroHTTonne"] = "PrixEuroHTTonne";
    DataColumnName["PrixAchatEuroHT"] = "PrixAchatEuroHT";
    DataColumnName["PrixNetEuroHTTonne"] = "PrixNetEuroHTTonne";
    DataColumnName["MontantEuroHT"] = "MontantEuroHT";
    DataColumnName["MontantEuroHTTonne"] = "MontantEuroHTTonne";
    DataColumnName["PrixTotalTransport"] = "PrixTotalTransport";
    DataColumnName["PrixTransportAffretement"] = "PrixTransportAffretement";
    DataColumnName["PoidsKg"] = "PoidsKg";
    DataColumnName["PoidsTonne"] = "PoidsTonne";
    DataColumnName["PoidsCommande"] = "PoidsCommande";
    DataColumnName["PoidsChargementAttribue"] = "PoidsChargementAttribue";
    DataColumnName["PoidsAttribuePourcentage"] = "PoidsAttribuePourcentage";
    DataColumnName["PoidsRestantALivrer"] = "PoidsRestantALivrer";
    DataColumnName["PoidsChargementDate"] = "PoidsChargementDate";
    DataColumnName["PoidsChargementDatePourcentage"] = "PoidsChargementDatePourcentage";
    DataColumnName["PoidsStockCentreDeTri"] = "PoidsStockCentreDeTri";
    DataColumnName["PoidsStockCentreDeTriPourcentage"] = "PoidsStockCentreDeTriPourcentage";
    DataColumnName["PoidsDechargementReceptionne"] = "PoidsDechargementReceptionne";
    DataColumnName["PoidsDechargementReceptionnePourcentage"] = "PoidsDechargementReceptionnePourcentage";
    DataColumnName["PoidsDontDispoMoisPrecedent"] = "PoidsDontDispoMoisPrecedent";
    DataColumnName["PoidsChargementTonne"] = "PoidsChargementTonne";
    DataColumnName["PoidsDechargementTonne"] = "PoidsDechargementTonne";
    DataColumnName["PoidsDeclareTonne"] = "PoidsDeclareTonne";
    DataColumnName["TonnageAnnuel"] = "TonnageAnnuel";
    DataColumnName["TonnageAnnuelPrecedent"] = "TonnageAnnuelPrecedent";
    DataColumnName["Collecte"] = "Collecte";
    DataColumnName["IncitationQualite"] = "IncitationQualite";
    DataColumnName["ListeComposant"] = "ListeComposant";
    DataColumnName["ListeProduitStandard"] = "ListeProduitStandard";
    DataColumnName["Id"] = "Id";
    DataColumnName["RefAdresse"] = "RefAdresse";
    DataColumnName["RefAdresseOrigine"] = "RefAdresseOrigine";
    DataColumnName["RefAdresseDestination"] = "RefAdresseDestination";
    DataColumnName["RefCamionType"] = "RefCamionType";
    DataColumnName["RefClientApplication"] = "RefClientApplication";
    DataColumnName["RefCommandeClient"] = "RefCommandeClient";
    DataColumnName["RefCommandeClientMensuelle"] = "RefCommandeClientMensuelle";
    DataColumnName["RefCommandeFournisseur"] = "RefCommandeFournisseur";
    DataColumnName["RefCommandeFournisseurStatut"] = "RefCommandeFournisseurStatut";
    DataColumnName["RefDescriptionControle"] = "RefDescriptionControle";
    DataColumnName["RefDescriptionCVQ"] = "RefDescriptionCVQ";
    DataColumnName["RefDescriptionReception"] = "RefDescriptionReception";
    DataColumnName["RefEntite"] = "RefEntite";
    DataColumnName["RefEquipementier"] = "RefEquipementier";
    DataColumnName["RefFicheControle"] = "RefFicheControle";
    DataColumnName["RefFonction"] = "RefFonction";
    DataColumnName["RefFournisseurTO"] = "RefFournisseurTO";
    DataColumnName["RefMessage"] = "RefMessage";
    DataColumnName["RefMontantIncitationQualite"] = "RefMontantIncitationQualite";
    DataColumnName["RefMotifAnomalieChargement"] = "RefMotifAnomalieChargement";
    DataColumnName["RefMotifAnomalieClient"] = "RefMotifAnomalieClient";
    DataColumnName["RefMotifAnomalieTransporteur"] = "RefMotifAnomalieTransporteur";
    DataColumnName["RefMotifCamionIncomplet"] = "RefMotifCamionIncomplet";
    DataColumnName["RefNonConformite"] = "RefNonConformite";
    DataColumnName["RefNonConformiteDemandeClientType"] = "RefNonConformiteDemandeClientType";
    DataColumnName["RefNonConformiteEtapeType"] = "RefNonConformiteEtapeType";
    DataColumnName["RefNonConformiteFamille"] = "RefNonConformiteFamille";
    DataColumnName["RefNonConformiteNature"] = "RefNonConformiteNature";
    DataColumnName["RefNonConformiteReponseClientType"] = "RefNonConformiteReponseClientType";
    DataColumnName["RefNonConformiteReponseFournisseurType"] = "RefNonConformiteReponseFournisseurType";
    DataColumnName["RefPrixReprise"] = "RefPrixReprise";
    DataColumnName["RefProcess"] = "RefProcess";
    DataColumnName["RefProduit"] = "RefProduit";
    DataColumnName["RefRepartition"] = "RefRepartition";
    DataColumnName["RefService"] = "RefService";
    DataColumnName["RefSurcoutCarburant"] = "RefSurcoutCarburant";
    DataColumnName["RefTitre"] = "RefTitre";
    DataColumnName["RefTransport"] = "RefTransport";
    DataColumnName["RefTransporteur"] = "RefTransporteur";
    DataColumnName["RepartitionD"] = "RepartitionD";
    DataColumnName["SurcoutCarburantRatio"] = "SurcoutCarburantRatio";
    DataColumnName["TransporteurLibelle"] = "TransporteurLibelle";
    DataColumnName["TransportPrix"] = "TransportPrix";
    DataColumnName["TransportPUHT"] = "TransportPUHT";
    DataColumnName["TransportPUHTDemande"] = "TransportPUHTDemande";
    DataColumnName["TransportTotalPrix"] = "TransportTotalPrix";
    DataColumnName["GenerePar"] = "GenerePar";
    DataColumnName["Janvier"] = "Janvier";
    DataColumnName["Fevrier"] = "Fevrier";
    DataColumnName["Mars"] = "Mars";
    DataColumnName["Avril"] = "Avril";
    DataColumnName["Mai"] = "Mai";
    DataColumnName["Juin"] = "Juin";
    DataColumnName["Juillet"] = "Juillet";
    DataColumnName["Aout"] = "Aout";
    DataColumnName["Septembre"] = "Septembre";
    DataColumnName["Octobre"] = "Octobre";
    DataColumnName["Novembre"] = "Novembre";
    DataColumnName["Decembre"] = "Decembre";
    DataColumnName["JanvierKg"] = "JanvierKg";
    DataColumnName["FevrierKg"] = "FevrierKg";
    DataColumnName["MarsKg"] = "MarsKg";
    DataColumnName["AvrilKg"] = "AvrilKg";
    DataColumnName["MaiKg"] = "MaiKg";
    DataColumnName["JuinKg"] = "JuinKg";
    DataColumnName["JuilletKg"] = "JuilletKg";
    DataColumnName["AoutKg"] = "AoutKg";
    DataColumnName["SeptembreKg"] = "SeptembreKg";
    DataColumnName["OctobreKg"] = "OctobreKg";
    DataColumnName["NovembreKg"] = "NovembreKg";
    DataColumnName["DecembreKg"] = "DecembreKg";
    DataColumnName["JanvierRegionPercent"] = "JanvierRegionPercent";
    DataColumnName["FevrierRegionPercent"] = "FevrierRegionPercent";
    DataColumnName["MarsRegionPercent"] = "MarsRegionPercent";
    DataColumnName["AvrilRegionPercent"] = "AvrilRegionPercent";
    DataColumnName["MaiRegionPercent"] = "MaiRegionPercent";
    DataColumnName["JuinRegionPercent"] = "JuinRegionPercent";
    DataColumnName["JuilletRegionPercent"] = "JuilletRegionPercent";
    DataColumnName["AoutRegionPercent"] = "AoutRegionPercent";
    DataColumnName["SeptembreRegionPercent"] = "SeptembreRegionPercent";
    DataColumnName["OctobreRegionPercent"] = "OctobreRegionPercent";
    DataColumnName["NovembreRegionPercent"] = "NovembreRegionPercent";
    DataColumnName["DecembreRegionPercent"] = "DecembreRegionPercent";
    DataColumnName["AnnuelPrecedentRegionPercent"] = "AnnuelPrecedentRegionPercent";
    DataColumnName["AnnuelRegionPercent"] = "AnnuelRegionPercent";
})(DataColumnName = exports.DataColumnName || (exports.DataColumnName = {}));
//Enumération pour les process de contact adresse
var ContactAdresseProcess;
(function (ContactAdresseProcess) {
    ContactAdresseProcess[ContactAdresseProcess["BonDeLivraison"] = 1] = "BonDeLivraison";
    ContactAdresseProcess[ContactAdresseProcess["DemandeEnlevement"] = 2] = "DemandeEnlevement";
    ContactAdresseProcess[ContactAdresseProcess["EtatTrimestriel"] = 3] = "EtatTrimestriel";
    ContactAdresseProcess[ContactAdresseProcess["FicheRepartition"] = 4] = "FicheRepartition";
    ContactAdresseProcess[ContactAdresseProcess["InteressementCentreDeTri"] = 5] = "InteressementCentreDeTri";
    ContactAdresseProcess[ContactAdresseProcess["RepriseCollectivite"] = 6] = "RepriseCollectivite";
    ContactAdresseProcess[ContactAdresseProcess["ReceptionMensuelle"] = 7] = "ReceptionMensuelle";
    ContactAdresseProcess[ContactAdresseProcess["IncitationQualite"] = 8] = "IncitationQualite";
    ContactAdresseProcess[ContactAdresseProcess["ControleurQualite"] = 9] = "ControleurQualite";
})(ContactAdresseProcess = exports.ContactAdresseProcess || (exports.ContactAdresseProcess = {}));
//Enumération for CommandeFournisseurStatut
var CommandeFournisseurStatut;
(function (CommandeFournisseurStatut) {
    CommandeFournisseurStatut[CommandeFournisseurStatut["Ouverte"] = 1] = "Ouverte";
    CommandeFournisseurStatut[CommandeFournisseurStatut["EnAttente"] = 2] = "EnAttente";
    CommandeFournisseurStatut[CommandeFournisseurStatut["Bloquee"] = 3] = "Bloquee";
})(CommandeFournisseurStatut = exports.CommandeFournisseurStatut || (exports.CommandeFournisseurStatut = {}));
//Enumération for CommandeFournisseurStatut
var EnvCommandeFournisseurStatutName;
(function (EnvCommandeFournisseurStatutName) {
    EnvCommandeFournisseurStatutName["Repartie"] = "Repartie";
    EnvCommandeFournisseurStatutName["Receptionnee"] = "Receptionnee";
    EnvCommandeFournisseurStatutName["Ouverte"] = "Ouverte";
    EnvCommandeFournisseurStatutName["EnAttente"] = "EnAttente";
    EnvCommandeFournisseurStatutName["Bloquee"] = "Bloquee";
    EnvCommandeFournisseurStatutName["DemandeEnlevement"] = "DemandeEnlevement";
    EnvCommandeFournisseurStatutName["Refusee"] = "Refusee";
})(EnvCommandeFournisseurStatutName = exports.EnvCommandeFournisseurStatutName || (exports.EnvCommandeFournisseurStatutName = {}));
//NonConformite file type
var NonConformiteFichierType;
(function (NonConformiteFichierType) {
    NonConformiteFichierType[NonConformiteFichierType["Client"] = 1] = "Client";
    NonConformiteFichierType[NonConformiteFichierType["Fournisseur"] = 2] = "Fournisseur";
    NonConformiteFichierType[NonConformiteFichierType["FacturationFournisseur"] = 3] = "FacturationFournisseur";
    NonConformiteFichierType[NonConformiteFichierType["Cloture"] = 4] = "Cloture";
})(NonConformiteFichierType = exports.NonConformiteFichierType || (exports.NonConformiteFichierType = {}));
//Data types
var DataType;
(function (DataType) {
    DataType["decimalNumber2"] = "decimalNumber2";
    DataType["decimalNumber3"] = "decimalNumber3";
    DataType["date"] = "date";
    DataType["dateTime"] = "dateTime";
    DataType["month"] = "month";
    DataType["monthNumber"] = "monthNumber";
    DataType["monthYear"] = "monthYear";
    DataType["quarterNumber"] = "quarterNumber";
    DataType["yearNumber"] = "yearNumber";
    DataType["bit"] = "bit";
    DataType["id"] = "id";
    DataType["intNumber"] = "intNumber";
    DataType["numeroCommande"] = "numeroCommande";
    DataType["text"] = "text";
    DataType["year"] = "year";
    DataType["percent"] = "percent";
})(DataType = exports.DataType || (exports.DataType = {}));
//Imput form element type
var InputFormComponentElementType;
(function (InputFormComponentElementType) {
    InputFormComponentElementType["NonConformiteCmt"] = "NonConformiteCmt";
    InputFormComponentElementType["LoginEmailLost"] = "LoginEmailLost";
    InputFormComponentElementType["NoEmail"] = "NoEmail";
})(InputFormComponentElementType = exports.InputFormComponentElementType || (exports.InputFormComponentElementType = {}));
//Search element type
var SearchElementType;
(function (SearchElementType) {
    SearchElementType["Entite"] = "Entite";
    SearchElementType["ContactAdresse"] = "ContactAdresse";
    SearchElementType["CommandeFournisseur"] = "CommandeFournisseur";
})(SearchElementType = exports.SearchElementType || (exports.SearchElementType = {}));
//Search result type
var SearchResultType;
(function (SearchResultType) {
    SearchResultType["CDT"] = "CDT";
    SearchResultType["Client"] = "Client";
    SearchResultType["Collectivite"] = "Collectivite";
    SearchResultType["Transporteur"] = "Transporteur";
})(SearchResultType = exports.SearchResultType || (exports.SearchResultType = {}));
// Dropwdown lists on html components
var ComponentDropdownType;
(function (ComponentDropdownType) {
    ComponentDropdownType["Pays"] = "Pays";
})(ComponentDropdownType = exports.ComponentDropdownType || (exports.ComponentDropdownType = {}));
//# sourceMappingURL=enums.js.map