/// <Propriété>
/// -----------------------------------------------------------------------------------------------------
/// Société Enviromatic sarl (Copyright)
/// 11 rue du Hainaut
/// 78570 Andrésy
/// -----------------------------------------------------------------------------------------------------
/// Projet : e-Valorplast (logiciel de gestion d'activité)
/// Création : 23/10/2018
/// ----------------------------------------------------------------------------------------------------- 
///

//Module system names
export enum ModuleName {
  Logistique = "Logistique",
  Annuaire = "Annuaire",
  Statistique = "Statistique",
  Messagerie = "Messagerie",
  Administration = "Administration",
  ModuleCollectivite = "ModuleCollectivite",
  Qualite = "Qualite",
  ModulePrestataire = "ModulePrestataire"
}

//Menu system names
export enum MenuName {
  AdministrationMenuActionType = "AdministrationMenuActionType",
  AdministrationMenuAdresseType = "AdministrationMenuAdresseType",
  AdministrationMenuAide = "AdministrationMenuAide",
  AdministrationMenuApplication = "AdministrationMenuApplication",
  AdministrationMenuApplicationProduitOrigine = "AdministrationMenuApplicationProduitOrigine",
  AdministrationMenuCamionType = "AdministrationMenuCamionType",
  AdministrationMenuCivilite = "AdministrationMenuCivilite",
  AdministrationMenuClientApplication = "AdministrationMenuClientApplication",
  AdministrationMenuDescriptionControle = "AdministrationMenuDescriptionControle",
  AdministrationMenuDescriptionCVQ = "AdministrationMenuDescriptionCVQ",
  AdministrationMenuDescriptionReception = "AdministrationMenuDescriptionReception",
  AdministrationMenuDocument = "AdministrationMenuDocument",
  AdministrationMenuEcoOrganisme = "AdministrationMenuEcoOrganisme",
  AdministrationMenuEntiteType = "AdministrationMenuEntiteType",
  AdministrationMenuEquipementier = "AdministrationMenuEquipementier",
  AdministrationMenuEquivalentCO2 = "AdministrationMenuEquivalentCO2",
  AdministrationMenuExtractionLogin = "AdministrationMenuExtractionLogin",
  AdministrationMenuFonction = "AdministrationMenuFonction",
  AdministrationMenuFormeContact = "AdministrationMenuFormeContact",
  AdministrationMenuFournisseurTO = "AdministrationMenuFournisseurTO",
  AdministrationMenuJourFerie = "AdministrationMenuJourFerie",
  AdministrationMenuMessageType = "AdministrationMenuMessageType",
  AdministrationMenuModeTransportEE = "AdministrationMenuModeTransportEE",
  AdministrationMenuMontantIncitationQualite = "AdministrationMenuMontantIncitationQualite",
  AdministrationMenuMotifAnomalieChargement = "AdministrationMenuMotifAnomalieChargement",
  AdministrationMenuMotifAnomalieClient = "AdministrationMenuMotifAnomalieClient",
  AdministrationMenuMotifAnomalieTransporteur = "AdministrationMenuMotifAnomalieTransporteur",
  AdministrationMenuMotifCamionIncomplet = "AdministrationMenuMotifCamionIncomplet",
  AdministrationMenuNonConformiteDemandeClientType = "AdministrationMenuNonConformiteDemandeClientType",
  AdministrationMenuNonConformiteFamille = "AdministrationMenuNonConformiteFamille",
  AdministrationMenuNonConformiteNature = "AdministrationMenuNonConformiteNature",
  AdministrationMenuNonConformiteReponseClientType = "AdministrationMenuNonConformiteReponseClientType",
  AdministrationMenuNonConformiteReponseFournisseurType = "AdministrationMenuNonConformiteReponseFournisseurType",
  AdministrationMenuParamEmail = "AdministrationMenuParamEmail",
  AdministrationMenuParametre = "AdministrationMenuParametre",
  AdministrationMenuPays = "AdministrationMenuPays",
  AdministrationMenuProcess = "AdministrationMenuProcess",
  AdministrationMenuProduit = "AdministrationMenuProduit",
  AdministrationMenuProduitGroupeReportingType = "AdministrationMenuProduitGroupeReportingType",
  AdministrationMenuProduitGroupeReporting = "AdministrationMenuProduitGroupeReporting",
  AdministrationMenuRegionEE = "AdministrationMenuRegionEE",
  AdministrationMenuRegionReporting = "AdministrationMenuRegionReporting",
  AdministrationMenuRepreneur = "AdministrationMenuRepreneur",
  AdministrationMenuRepriseType = "AdministrationMenuRepriseType",
  AdministrationMenuRessource = "AdministrationMenuRessource",
  AdministrationMenuSAGECodeTransport = "AdministrationMenuSAGECodeTransport",
  AdministrationMenuSecurite = "AdministrationMenuSecurite",
  AdministrationMenuStandard = "AdministrationMenuStandard",
  AdministrationMenuSuiviLogin = "AdministrationMenuSuiviLogin",
  AdministrationMenuUtilisateur = "AdministrationMenuUtilisateur",
  AdministrationMenuService = "AdministrationMenuService",
  AdministrationMenuTicket = "AdministrationMenuTicket",
  AdministrationMenuTitre = "AdministrationMenuTitre",
  AdministrationMenuUtilisateurInactif = "AdministrationMenuUtilisateurInactif",
  AnnuaireMenuNbAffretementTransporteur = "AnnuaireMenuNbAffretementTransporteur",
  AnnuaireMenuIncitationQualite = "AnnuaireMenuIncitationQualite",
  AnnuaireMenuEmailNoteCreditCollectivite = "AnnuaireMenuEmailNoteCreditCollectivite",
  AnnuaireMenuSuiviEnvois = "AnnuaireMenuSuiviEnvois",
  AnnuaireMenuEntite = "AnnuaireMenuEntite",
  AnnuaireMenuExtractionAction = "AnnuaireMenuExtractionAction",
  AnnuaireMenuExtractionAnnuaire = "AnnuaireMenuExtractionAnnuaire",
  LogistiqueMenuChargementAnnule = "LogistiqueMenuChargementAnnule",
  LogistiqueMenuCommandeClient = "LogistiqueMenuCommandeClient",
  LogistiqueMenuCommandeFournisseur = "LogistiqueMenuCommandeFournisseur",
  LogistiqueMenuEtatCoutTransport = "LogistiqueMenuEtatCoutTransport",
  LogistiqueMenuExportSAGE = "LogistiqueMenuExportSAGE",
  LogistiqueMenuExtractionTransport = "LogistiqueMenuExtractionTransport",
  LogistiqueMenuExtractionOscar = "LogistiqueMenuExtractionOscar",
  LogistiqueMenuImporterTransport = "LogistiqueMenuImporterTransport",
  LogistiqueMenuImpression = "LogistiqueMenuImpression",
  LogistiqueMenuLotDisponible = "LogistiqueMenuLotDisponible",
  LogistiqueMenuModifierTransport = "LogistiqueMenuModifierTransport",
  LogistiqueMenuModifierTousPrixTransport = "LogistiqueMenuModifierTousPrixTransport",
  LogistiqueMenuPrixReprise = "LogistiqueMenuPrixReprise",
  LogistiqueMenuRepartition = "LogistiqueMenuRepartition",
  LogistiqueMenuSupprimerTransportEnMasse = "LogistiqueMenuSupprimerTransportEnMasse",
  LogistiqueMenuSurcoutCarburant = "LogistiqueMenuSurcoutCarburant",
  LogistiqueMenuTransportDemandeEnlevement = "LogistiqueMenuTransportDemandeEnlevement",
  LogistiqueMenuTransportCommande = "LogistiqueMenuTransportCommande",
  LogistiqueMenuTransportCommandeEnCours = "LogistiqueMenuTransportCommandeEnCours",
  LogistiqueMenuTransportCommandeModifiee = "LogistiqueMenuTransportCommandeModifiee",
  LogistiqueMenuTransportNonValide = "LogistiqueMenuTransportNonValide",
  LogistiqueMenuValiderNouveauPrixTransport = "LogistiqueMenuValiderNouveauPrixTransport",
  LogistiqueMenuDelaiCommandeEnlevement = "LogistiqueMenuDelaiCommandeEnlevement",
  LogistiqueMenuEtatReception = "LogistiqueMenuEtatReception",
  LogistiqueMenuEtatReceptionEmballagePlastique = "LogistiqueMenuEtatReceptionEmballagePlastique",
  LogistiqueMenuEtatSuiviTonnageRecycleur = "LogistiqueMenuEtatSuiviTonnageRecycleur",
  LogistiqueMenuEtatDesFluxDev = "LogistiqueMenuEtatDesFluxDev",
  LogistiqueMenuEtatDesFluxDevLeko = "LogistiqueMenuEtatDesFluxDevLeko",
  LogistiqueMenuEtatTarifTransporteurClient = "LogistiqueMenuEtatTarifTransporteurClient",
  LogistiqueMenuExtractionLeko = "LogistiqueMenuExtractionLeko",
  LogistiqueMenuPartMarcheTransporteur = "LogistiqueMenuPartMarcheTransporteur",
  LogistiqueMenuEtatKmMoyen = "LogistiqueMenuEtatKmMoyen",
  LogistiqueMenuSuiviCommandeClient = "LogistiqueMenuSuiviCommandeClient",
  LogistiqueMenuSuiviCommandeClientProduit = "LogistiqueMenuSuiviCommandeClientProduit",
  LogistiqueMenuEtatReceptionProduit = "LogistiqueMenuEtatReceptionProduit",
  LogistiqueMenuEtatReceptionProduitDR = "LogistiqueMenuEtatReceptionProduitDR",
  LogistiqueMenuExtractionReception = "LogistiqueMenuExtractionReception",
  LogistiqueMenuEtatReceptionFournisseurChargement = "LogistiqueMenuEtatReceptionFournisseurChargement",
  LogistiqueMenuExtractionCommande = "LogistiqueMenuExtractionCommande",
  LogistiqueMenuEtatDesPoids = "LogistiqueMenuEtatDesPoids",
  LogistiqueMenuEtatTonnageParProcess = "LogistiqueMenuEtatTonnageParProcess",
  LogistiqueMenuEtatVenteAnnuelleProduitClient = "LogistiqueMenuEtatVenteAnnuelleProduitClient",
  LogistiqueMenuEtatDestinationAnnuelleProduitClient = "LogistiqueMenuEtatDestinationAnnuelleProduitClient",
  LogistiqueMenuSuiviFacturationHC = "LogistiqueMenuSuiviFacturationHC",
  LogistiqueMenuTonnageCollectiviteProduit = "LogistiqueMenuTonnageCollectiviteProduit",
  LogistiqueMenuTonnageCDTProduitComposant = "LogistiqueMenuTonnageCDTProduitComposant",
  LogistiqueMenuTonnageCLSousContrat = "LogistiqueMenuTonnageCLSousContrat",
  LogistiqueMenuListeProduit = "LogistiqueMenuListeProduit",
  LogistiqueMenuEtatDesEnlevements = "LogistiqueMenuEtatDesEnlevements",
  LogistiqueMenuPoidsMoyenChargementProduit = "LogistiqueMenuPoidsMoyenChargementProduit",
  MenuVisualisationAnnuaire = "MenuVisualisationAnnuaire",
  MenuDocuments = "MenuDocuments",
  MessagerieMenuMessage = "MessagerieMenuMessage",
  MessagerieMenuVisualisation = "MessagerieMenuVisualisation",
  ModuleCollectiviteMenuAccueil = "ModuleCollectiviteMenuAccueil",
  ModuleCollectiviteMenuDocuments = "ModuleCollectiviteMenuDocuments",
  ModuleCollectiviteMenuPrixReprise = "ModuleCollectiviteMenuPrixReprise",
  ModulePrestataireMenuCommandeFournisseur = "ModulePrestataireMenuCommandeFournisseur",
  ModuleCollectiviteMenuStatistiques = "ModuleCollectiviteMenuStatistiques",
  ModuleCollectiviteMenuVisualisationAnnuaire = "ModuleCollectiviteMenuVisualisationAnnuaire",
  QualiteMenuControle = "QualiteMenuControle",
  QualiteMenuNonConformite = "QualiteMenuNonConformite",
  QualiteMenuRepartitionControleClient = "QualiteMenuRepartitionControleClient",
  QualiteMenuExtractionFicheControle = "QualiteMenuExtractionFicheControle",
  QualiteMenuExtractionControle = "QualiteMenuExtractionControle",
  QualiteMenuExtractionNonConformite = "QualiteMenuExtractionNonConformite",
  QualiteMenuExtractionCVQ = "QualiteMenuExtractionCVQ",
  QualiteMenuEtatIncitationQualite = "QualiteMenuEtatIncitationQualite",
  QualiteMenuEtatControleReception = "QualiteMenuEtatControleReception",
  AnnuaireMenuEvolutionTonnage = "AnnuaireMenuEvolutionTonnage"
}
//Actions system names
export enum ActionName {
  ValidateTransportPrice = "ValidateTransportPrice",
  RejectTransportPrice = "RejectTransportPrice",
  DeleteTransport = "DeleteTransport",
  SetEnAttente = "SetEnAttente",
  ChangeMoisDechargementPrevu = "ChangeMoisDechargementPrevu",
  CopyPrixReprise = "CopyPrixReprise",
  CentreDeTriForUtilisateur = "CentreDeTriForUtilisateur",
  DeactivateUtilisateur = "DeactivateUtilisateur",
  ValidateRepartition = "ValidateRepartition"
}

//Habilitations Module logistique
export enum HabilitationLogistique {
  Administrateur = "Administrateur", Transporteur = "Transporteur", Client = "Client", Utilisateur = "Utilisateur", CentreDeTri = "CentreDeTri"
}
//Habilitations de l"annuaire
export enum HabilitationAnnuaire {
  Administrateur = "Administrateur", Visualisation = "Visualisation", Utilisateur = "Utilisateur"
}
//Habilitations Module statistiques
export enum HabilitationStatistique {
  Utilisateur = "Utilisateur"
}
//Habilitations Module messagerie
export enum HabilitationMessagerie {
  Administrateur = "Administrateur", Utilisateur = "Utilisateur"
}
//Habilitations Module administration
export enum HabilitationAdministration {
  Administrateur = "Administrateur"
}
//Habilitations module collectivité
export enum HabilitationModuleCollectivite {
  Administrateur = "Administrateur", Utilisateur = "Utilisateur"
}
//Habilitations module CDT
export enum HabilitationModuleCentreDeTri {
  Administrateur = "Administrateur", Utilisateur = "Utilisateur"
}
//Habilitations Module qualité
export enum HabilitationQualite {
  Administrateur = "Administrateur", Client = "Client", Utilisateur = "Utilisateur", Fournisseur = "Fournisseur"
}
//Habilitations Module prestataire
export enum HabilitationModulePrestataire {
  Administrateur = "Administrateur", Client = "Client", Fournisseur = "Fournisseur", Transporteur = "Transporteur"
}

//Enumération pour les noms de colonne
export enum DataColumnName {
  ActionCmt = "ActionCmt",
  ActionDate = "ActionDate",
  ActionLibelle = "ActionLibelle",
  ActionTypeDocumentType = "ActionTypeDocumentType",
  ActionTypeLibelle = "ActionTypeLibelle",
  Adresse = "Adresse",
  AdresseLibelle = "AdresseLibelle",
  AdresseAdr1 = "AdresseAdr1",
  AdresseAdr2 = "AdresseAdr2",
  AdresseCodePostal = "AdresseCodePostal",
  AdresseVille = "AdresseVille",
  AdresseTel = "AdresseTel",
  AdresseEmail = "AdresseEmail",
  AdresseSiteWeb = "AdresseSiteWeb",
  TexteContactAdresseList = "TexteContactAdresseList",
  TexteAdresseList = "TexteAdresseList",
  AdresseActif = "AdresseActif",
  AdresseDestinationCP = "AdresseDestinationCP",
  AdresseDestinationDpt = "AdresseDestinationDpt",
  AdresseDestinationTypeLibelle = "AdresseDestinationTypeLibelle",
  AdresseDestinationVille = "AdresseDestinationVille",
  AdresseHoraires = "AdresseHoraires",
  AdresseOrigineCP = "AdresseOrigineCP",
  AdresseOrigineTypeLibelle = "AdresseOrigineTypeLibelle",
  AdresseOrigineVille = "AdresseOrigineVille",
  AdresseTypeLibelle = "AdresseTypeLibelle",
  AideComposant = "AideComposant",
  AideValeurHTML = "AideValeurHTML",
  AideLibelleFRFR = "AideLibelleFRFR",
  AideLibelleENGB = "AideLibelleENGB",
  Annee = "Annee",
  AnneeNb = "AnneeNb",
  AnneeTexte = "AnneeTexte",
  ApplicationLibelle = "ApplicationLibelle",
  ApplicationProduitOrigineLibelle = "ApplicationProduitOrigineLibelle",
  CamionTypeLibelle = "CamionTypeLibelle",
  CentreDeTriLibelle = "CentreDeTriLibelle",
  CentreDeTriListeCamionTypes = "CentreDeTriListeCamionTypes",
  CiviliteLibelle = "CiviliteLibelle",
  ClientLibelle = "ClientLibelle",
  CommandeClientMensuelleD = "CommandeClientMensuelleD",
  CommandeClientMensuellePoids = "CommandeClientMensuellePoids",
  CommandeClientPositionne = "CommandeClientPositionne",
  CommandeFournisseurAdresseOrigineDpt = "CommandeFournisseurAdresseOrigineDpt",
  CommandeFournisseurAdresseOrigineVille = "CommandeFournisseurAdresseOrigineVille",
  CommandeFournisseurCamionComplet = "CommandeFournisseurCamionComplet",
  CommandeFournisseurCamionCompletInvisible = "CommandeFournisseurCamionCompletInvisible",
  CommandeFournisseurCB = "CommandeFournisseurCB",
  CommandeFournisseurChargementAnnulePar = "CommandeFournisseurChargementAnnulePar",
  CommandeFournisseurChargementEffectue = "CommandeFournisseurChargementEffectue",
  CommandeFournisseurCmtAnomalieChargement = "CommandeFournisseurCmtAnomalieChargement",
  CommandeFournisseurCmtAnomalieTransporteur = "CommandeFournisseurCmtAnomalieTransporteur",
  CommandeFournisseurCmtAnomalieClient = "CommandeFournisseurCmtAnomalieClient",
  CommandeFournisseurCmtChargementAnnule = "CommandeFournisseurCmtChargementAnnule",
  CommandeFournisseurCmtFournisseur = "CommandeFournisseurCmtFournisseur",
  CommandeFournisseurCVQ = "CommandeFournisseurCVQ",
  CommandeFournisseurDAffretement = "CommandeFournisseurDAffretement",
  CommandeFournisseurDateCreation = "CommandeFournisseurDateCreation",
  CommandeFournisseurDAnomalieChargement = "CommandeFournisseurDAnomalieChargement",
  CommandeFournisseurDAnomalieTransporteur = "CommandeFournisseurDAnomalieTransporteur",
  CommandeFournisseurDAnomalieClient = "CommandeFournisseurDAnomalieClient",
  CommandeFournisseurDChargement = "CommandeFournisseurDChargement",
  CommandeFournisseurDChargementAnnule = "CommandeFournisseurDChargementAnnule",
  CommandeFournisseurDChargementPrevue = "CommandeFournisseurDChargementPrevue",
  CommandeFournisseurDDechargement = "CommandeFournisseurDDechargement",
  CommandeFournisseurDDechargementInvisible = "CommandeFournisseurDDechargementInvisible",
  CommandeFournisseurDDechargementPrevue = "CommandeFournisseurDDechargementPrevue",
  CommandeFournisseurDDisponibilite = "CommandeFournisseurDDisponibilite",
  CommandeFournisseurDelaiChargement = "CommandeFournisseurDelaiChargement",
  CommandeFournisseurDelaiCommande = "CommandeFournisseurDelaiCommande",
  CommandeFournisseurDTraitementAnomalieChargementInvisible = "CommandeFournisseurDTraitementAnomalieChargementInvisible",
  CommandeFournisseurDTraitementAnomalieClientInvisible = "CommandeFournisseurDTraitementAnomalieClientInvisible",
  CommandeFournisseurDTraitementAnomalieTransporteurInvisible = "CommandeFournisseurDTraitementAnomalieTransporteurInvisible",
  CommandeFournisseurDTraitementAnomalieChargement = "CommandeFournisseurDTraitementAnomalieChargement",
  CommandeFournisseurDTraitementAnomalieClient = "CommandeFournisseurDTraitementAnomalieClient",
  CommandeFournisseurDTraitementAnomalieTransporteur = "CommandeFournisseurDTraitementAnomalieTransporteur",
  CommandeFournisseurFicheControle = "CommandeFournisseurFicheControle",
  CommandeFournisseurHoraireDechargementPrevu = "CommandeFournisseurHoraireDechargementPrevu",
  CommandeFournisseurImprime = "CommandeFournisseurImprime",
  CommandeFournisseurKm = "CommandeFournisseurKm",
  CommandeFournisseurLimiteExclusivite = "CommandeFournisseurLimiteExclusivite",
  CommandeFournisseurLotControle = "CommandeFournisseurLotControle",
  CommandeFournisseurMixte = "CommandeFournisseurMixte",
  CommandeFournisseurMoisDechargementPrevu = "CommandeFournisseurMoisDechargementPrevu",
  CommandeFournisseurNbBalleChargement = "CommandeFournisseurNbBalleChargement",
  CommandeFournisseurNbBalleDechargement = "CommandeFournisseurNbBalleDechargement",
  CommandeFournisseurNumeroCommande = "CommandeFournisseurNumeroCommande",
  CommandeFournisseurNumeroAffretement = "CommandeFournisseurNumeroAffretement",
  CommandeFournisseurPoidsChargement = "CommandeFournisseurPoidsChargement",
  CommandeFournisseurPoidsDechargement = "CommandeFournisseurPoidsDechargement",
  CommandeFournisseurPoidsReparti = "CommandeFournisseurPoidsReparti",
  CommandeFournisseurPrixTransportHT = "CommandeFournisseurPrixTransportHT",
  CommandeFournisseurPrixTransportSupplementHT = "CommandeFournisseurPrixTransportSupplementHT",
  CommandeFournisseurStatut = "CommandeFournisseurStatut",
  CommandeFournisseurPrixTonneHT = "CommandeFournisseurPrixTonneHT",
  CommandeFournisseurRefExt = "CommandeFournisseurRefExt",
  CommandeFournisseurSurcoutCarburantHT = "CommandeFournisseurSurcoutCarburantHT",
  CommandeFournisseurNonConformite = "CommandeFournisseurNonConformite",
  CommandeFournisseurNonConformiteInvisible = "CommandeFournisseurNonConformiteInvisible",
  CommandeFournisseurNbTotalLivraison = "CommandeFournisseurNbTotalLivraison",
  CommandeFournisseurNbTotalLivraisonAControler = "CommandeFournisseurNbTotalLivraisonAControler",
  CommandeFournisseurNbTotalLivraisonControlees = "CommandeFournisseurNbTotalLivraisonControlees",
  CommandeFournisseurTauxControle = "CommandeFournisseurTauxControle",
  ComposantLibelle = "ComposantLibelle",
  CollectiviteLibelle = "CollectiviteLibelle",
  Connexions = "Connexions",
  ContactAdresseActif = "ContactAdresseActif",
  ContactAdresseCmt = "ContactAdresseCmt",
  ContactAdresseCmtServiceFonction = "ContactAdresseCmtServiceFonction",
  ContactAdresseEmail = "ContactAdresseEmail",
  ContactAdresseIsUser = "ContactAdresseIsUser",
  ContactAdresseListeFonctionServices = "ContactAdresseListeFonctionServices",
  ContactAdresseListeProcesss = "ContactAdresseListeProcesss",
  ContactAdresseTel = "ContactAdresseTel",
  ContactAdresseTelMobile = "ContactAdresseTelMobile",
  ContactPrenom = "ContactPrenom",
  ContactNom = "ContactNom",
  ContratCollectiviteDebut = "ContratCollectiviteDebut",
  ContratCollectiviteFin = "ContratCollectiviteFin",
  ContratIncitationQualiteDebut = "ContratIncitationQualiteDebut",
  ContratIncitationQualiteFin = "ContratIncitationQualiteFin",
  ContratLibelle = "ContratLibelle",
  ControleCmt = "ControleCmt",
  ControleDControle = "ControleDControle",
  ControlePoids = "ControlePoids",
  ControlePoidsTotal = "ControlePoidsTotal",
  ControlePoidsTotalIndesirable = "ControlePoidsTotalIndesirable",
  ControlePourcentageIndesirable = "ControlePourcentageIndesirable",
  Controles = "Controles",
  CreationPar = "CreationPar",
  CVQCmt = "CVQCmt",
  CVQDCVQ = "CVQDCVQ",
  DescriptionControleActif = "DescriptionControleActif",
  DescriptionControleCalculLimiteConformite = "DescriptionControleCalculLimiteConformite",
  DescriptionControleLibelleFRFR = "DescriptionControleLibelleFRFR",
  DescriptionControleLibelleENGB = "DescriptionControleLibelleENGB",
  DescriptionControleOrdre = "DescriptionControleOrdre",
  DescriptionCVQActif = "DescriptionCVQActif",
  DescriptionCVQLibelleFRFR = "DescriptionCVQLibelleFRFR",
  DescriptionCVQLibelleENGB = "DescriptionCVQLibelleENGB",
  DescriptionCVQLimiteBasse = "DescriptionCVQLimiteBasse",
  DescriptionCVQLimiteHaute = "DescriptionCVQLimiteHaute",
  DescriptionCVQOrdre = "DescriptionCVQOrdre",
  DescriptionReceptionActif = "DescriptionReceptionActif",
  DescriptionReceptionLibelleFRFR = "DescriptionReceptionLibelleFRFR",
  DescriptionReceptionLibelleENGB = "DescriptionReceptionLibelleENGB",
  DescriptionReceptionOuiFRFR = "DescriptionReceptionOuiFRFR",
  DescriptionReceptionOuiENGB = "DescriptionReceptionOuiENGB",
  DescriptionReceptionNonFRFR = "DescriptionReceptionNonFRFR",
  DescriptionReceptionNonENGB = "DescriptionReceptionNonENGB",
  DescriptionReceptionOrdre = "DescriptionReceptionOrdre",
  D = "D",
  DocumentActif = "DocumentActif",
  DocumentDescription = "DocumentDescription",
  DocumentLibelle = "DocumentLibelle",
  DLogin = "DLogin",
  DLogout = "DLogout",
  DRActif = "DRActif",
  EconomieCO2KgT = "EconomieCO2KgT",
  EcoOrganismeLibelle = "EcoOrganismeLibelle",
  EmailDEnvoi = "EmailDEnvoi",
  EntiteActionnaireProprietaire = "EntiteActionnaireProprietaire",
  EntiteAssujettiTVA = "EntiteAssujettiTVA",
  EntiteCapacite = "EntiteCapacite",
  EntiteCodeTVA = "EntiteCodeTVA",
  EntiteCodeValorisation = "EntiteCodeValorisation",
  EntiteContratCollectiviteActif = "EntiteContratCollectiviteActif",
  EntiteDimensionBalle = "EntiteDimensionBalle",
  EntiteExploitant = "EntiteExploitant",
  EntiteExportSAGE = "EntiteExportSAGE",
  EntiteIdNational = "EntiteIdNational",
  EntiteLibelle = "EntiteLibelle",
  EntiteListe = "EntiteListe",
  EntiteListeCentreDeTriActifs = "EntiteListeCentreDeTriActifs",
  EntiteListeCentreDeTriInactifs = "EntiteListeCentreDeTriInactifs",
  EntiteListeCentreDeTriActifInterdits = "EntiteListeCentreDeTriActifInterdits",
  EntiteListeCollectiviteActifs = "EntiteListeCollectiviteActifs",
  EntiteListeCollectiviteInactifs = "EntiteListeCollectiviteInactifs",
  EntiteListeContratCollectivites = "EntiteListeContratCollectivites",
  EntiteListeClientActifInterdits = "EntiteListeClientActifInterdits",
  EntiteListeDocumentPublic = "EntiteListeDocumentPublic",
  EntiteListeDocumentValorplast = "EntiteListeDocumentValorplast",
  EntiteTransporteurActifInterdits = "EntiteTransporteurActifInterdits",
  EntiteListeIndustrielActifs = "EntiteListeIndustrielActifs",
  EntiteListeProcesss = "EntiteListeProcesss",
  EntiteListeProduits = "EntiteListeProduits",
  EntiteListeProduitInterdits = "EntiteListeProduitInterdits",
  EntiteListeStandards = "EntiteListeStandards",
  EntitePopulationContratN = "EntitePopulationContratN",
  EntiteReconductionIncitationQualite = "EntiteReconductionIncitationQualite",
  EntiteRepartitionMensuelle = "EntiteRepartitionMensuelle",
  EntiteSousContrat = "EntiteSousContrat",
  EntiteActif = "EntiteActif",
  EntiteAdelphe = "EntiteAdelphe",
  EntiteSAGECodeComptable = "EntiteSAGECodeComptable",
  EntiteSAGECompteTiers = "EntiteSAGECompteTiers",
  EntiteSurcoutCarburant = "EntiteSurcoutCarburant",
  EntiteTypeLibelle = "EntiteTypeLibelle",
  EntiteTypeLibelleENGB = "EntiteTypeLibelleENGB",
  EntiteTypeLibelleFRFR = "EntiteTypeLibelleFRFR",
  EntiteTypeListe = "EntiteTypeListe",
  EntiteCodeCITEO = "EntiteCodeCITEO",
  EntiteCmt = "EntiteCmt",
  EntiteVisibiliteAffretementCommun = "EntiteVisibiliteAffretementCommun",
  EquipementierLibelle = "EquipementierLibelle",
  EquivalentCO2Libelle = "EquivalentCO2Libelle",
  EquivalentCO2Ordre = "EquivalentCO2Ordre",
  EquivalentCO2Ratio = "EquivalentCO2Ratio",
  EquivalentCO2Actif = "EquivalentCO2Actif",
  FicheControleControle = "FicheControleControle",
  FicheControleCVQ = "FicheControleCVQ",
  FicheControleReception = "FicheControleReception",
  FicheControleNumeroLotUsine = "FicheControleNumeroLotUsine",
  FicheControleReserve = "FicheControleReserve",
  FicheControleCmt = "FicheControleCmt",
  FicheControleControleur = "FicheControleControleur",
  FonctionLibelle = "FonctionLibelle",
  FormeContactLibelle = "FormeContactLibelle",
  FournisseurLibelle = "FournisseurLibelle",
  FournisseurTOLibelle = "FournisseurTOLibelle",
  JourFerie = "JourFerie",
  ListeDR = "ListeDR",
  MessageLibelle = "MessageLibelle",
  MessageCorps = "MessageCorps",
  MessageCorpsHTML = "MessageCorpsHTML",
  MessageDDebut = "MessageDDebut",
  MessageDFin = "MessageDFin",
  MessageTitre = "MessageTitre",
  MessageTypeLibelle = "MessageTypeLibelle",
  MessageVisualisationD = "MessageVisualisationD",
  MessageVisualisationConfirme = "MessageVisualisationConfirme",
  MessageVisualisationPar = "MessageVisualisationPar",
  ModeTransportEELibelle = "ModeTransportEELibelle",
  ModificationPar = "ModificationPar",
  Montant = "Montant",
  MotifAnomalieChargementLibelle = "MotifAnomalieChargementLibelle",
  MotifAnomalieClientLibelle = "MotifAnomalieClientLibelle",
  MotifAnomalieTransporteurLibelle = "MotifAnomalieTransporteurLibelle",
  MotifCamionIncompletLibelle = "MotifCamionIncompletLibelle",
  Nb = "Nb",
  NonConformiteDateCreation = "NonConformiteDateCreation",
  NonConformiteDescrClient = "NonConformiteDescrClient",
  NonConformiteDescrValorplast = "NonConformiteDescrValorplast",
  NonConformiteIF = "NonConformiteIF",
  NonConformiteIFClient = "NonConformiteIFClient",
  NonConformiteIFFournisseur = "NonConformiteIFFournisseur",
  NonConformiteIFClientCmtFacturation = "NonConformiteIFClientCmtFacturation",
  NonConformiteIFClientDFacture = "NonConformiteIFClientDFacture",
  NonConformiteIFClientFactureMontant = "NonConformiteIFClientFactureMontant",
  NonConformiteIFClientFactureNro = "NonConformiteIFClientFactureNro",
  NonConformiteIFFournisseurAttenteBonCommandeNro = "NonConformiteIFFournisseurAttenteBonCommandeNro",
  NonConformiteIFFournisseurBonCommandeNro = "NonConformiteIFFournisseurBonCommandeNro",
  NonConformiteIFFournisseurCmtFacturation = "NonConformiteIFFournisseurCmtFacturation",
  NonConformiteIFFournisseurDeductionTonnage = "NonConformiteIFFournisseurDeductionTonnage",
  NonConformiteIFFournisseurFactureMontant = "NonConformiteIFFournisseurFactureMontant",
  NonConformiteIFFournisseurFactureNro = "NonConformiteIFFournisseurFactureNro",
  NonConformiteIFFournisseurRetourLot = "NonConformiteIFFournisseurRetourLot",
  NonConformiteIFFournisseurTransmissionFacturation = "NonConformiteIFFournisseurTransmissionFacturation",
  NonConformiteListeFamille = "NonConformiteListeFamille",
  NonConformiteOriginePlanActionSaisi = "NonConformiteOriginePlanActionSaisi",
  NonConformitePlanAction = "NonConformitePlanAction",
  NonConformitePlanActionNonConcerne = "NonConformitePlanActionNonConcerne",
  NonConformitePriseEnCharge = "NonConformitePriseEnCharge",
  NonConformiteMontantPriseEnCharge = "NonConformiteMontantPriseEnCharge",
  NonConformiteIFFournisseurFacture = "NonConformiteIFFournisseurFacture",
  NonConformiteActionDR = "NonConformiteActionDR",
  NonConformiteDTransmissionFournisseur = "NonConformiteDTransmissionFournisseur",
  NonConformiteCmtPriseEnCharge = "NonConformiteCmtPriseEnCharge",
  NonConformiteCmtReponseFournisseur = "NonConformiteCmtReponseFournisseur",
  NonConformiteCmtReponseClient = "NonConformiteCmtReponseClient",
  NonConformiteEtapeDValide = "NonConformiteEtapeDValide",
  NonConformiteEtapeLibelle = "NonConformiteEtapeLibelle",
  NonConformiteCloturee = "NonConformiteCloturee",
  NonConformiteClotureeInvisible = "NonConformiteClotureeInvisible",
  NonConformiteDemandeClientTypeActif = "NonConformiteDemandeClientTypeActif",
  NonConformiteDemandeClientTypeLibelle = "NonConformiteDemandeClientTypeLibelle",
  NonConformiteDemandeClientTypeLibelleFRFR = "NonConformiteDemandeClientTypeLibelleFRFR",
  NonConformiteDemandeClientTypeLibelleENGB = "NonConformiteDemandeClientTypeLibelleENGB",
  NonConformiteAccordFournisseurTypeLibelle = "NonConformiteAccordFournisseurTypeLibelle",
  NonConformiteFamilleActif = "NonConformiteFamilleActif",
  NonConformiteFamilleIncitationQualite = "NonConformiteFamilleIncitationQualite",
  NonConformiteFamilleLibelle = "NonConformiteFamilleLibelle",
  NonConformiteFamilleLibelleFRFR = "NonConformiteFamilleLibelleFRFR",
  NonConformiteFamilleLibelleENGB = "NonConformiteFamilleLibelleENGB",
  NonConformiteNatureActif = "NonConformiteNatureActif",
  NonConformiteNatureIncitationQualite = "NonConformiteNatureIncitationQualite",
  NonConformiteNatureLibelle = "NonConformiteNatureLibelle",
  NonConformiteNatureLibelleFRFR = "NonConformiteNatureLibelleFRFR",
  NonConformiteNatureLibelleENGB = "NonConformiteNatureLibelleENGB",
  NonConformiteReponseClientTypeActif = "NonConformiteReponseClientTypeActif",
  NonConformiteReponseClientTypeLibelle = "NonConformiteReponseClientTypeLibelle",
  NonConformiteReponseClientTypeLibelleFRFR = "NonConformiteReponseClientTypeLibelleFRFR",
  NonConformiteReponseClientTypeLibelleENGB = "NonConformiteReponseClientTypeLibelleENGB",
  NonConformiteReponseFournisseurTypeActif = "NonConformiteReponseFournisseurTypeActif",
  NonConformiteReponseFournisseurTypeLibelle = "NonConformiteReponseFournisseurTypeLibelle",
  NonConformiteReponseFournisseurTypeLibelleFRFR = "NonConformiteReponseFournisseurTypeLibelleFRFR",
  NonConformiteReponseFournisseurTypeLibelleENGB = "NonConformiteReponseFournisseurTypeLibelleENGB",
  ParamEmailActif = "ParamEmailActif",
  ParamEmailComptePOP = "ParamEmailComptePOP",
  ParamEmailEmailExpediteur = "ParamEmailEmailExpediteur",
  ParamEmailLibelleExpediteur = "ParamEmailLibelleExpediteur",
  ParametreLibelle = "ParametreLibelle",
  ParametreServeur = "ParametreServeur",
  ParametreValeurNumerique = "ParametreValeurNumerique",
  ParametreValeurTexte = "ParametreValeurTexte",
  ParametreValeurHTML = "ParametreValeurHTML",
  ParcoursKm = "ParcoursKm",
  PaysActif = "PaysActif",
  PaysDestinbationLibelle = "PaysDestinbationLibelle",
  PaysLibelle = "PaysLibelle",
  PaysCodeISO = "PaysCodeISO",
  Periode = "Periode",
  PoidsRepartiCITEO = "PoidsRepartiCITEO",
  PoidsRepartiAdelphe = "PoidsRepartiAdelphe",
  PoidsRepartiLeko = "PoidsRepartiLeko",
  Pourcentage = "Pourcentage",
  PremieresConnexions = "PremieresConnexions",
  PrixRepriseD = "PrixRepriseD",
  PrixReprisePUHT = "PrixReprisePUHT",
  PrixReprisePUHTSurtri = "PrixReprisePUHTSurtri",
  PrixReprisePUHTTransport = "PrixReprisePUHTTransport",
  ProcessLibelle = "ProcessLibelle",
  ProduitLibelle = "ProduitLibelle",
  ProduitActif = "ProduitActif",
  ProduitComposant = "ProduitComposant",
  ProduitNomCommercial = "ProduitNomCommercial",
  ProduitNomCommun = "ProduitNomCommun",
  ProduitNumeroStatistique = "ProduitNumeroStatistique",
  ProduitCo2KgParT = "ProduitCo2KgParT",
  ProduitCodeListeVerte = "ProduitCodeListeVerte",
  ProduitCodeEE = "ProduitCodeEE",
  ProduitCmt = "ProduitCmt",
  ProduitCmtFournisseur = "ProduitCmtFournisseur",
  ProduitCmtTransporteur = "ProduitCmtTransporteur",
  ProduitCmtClient = "ProduitCmtClient",
  ProduitPUHTSurtri = "ProduitPUHTSurtri",
  ProduitPUHTTransport = "ProduitPUHTTransport",
  ProduitGroupeReportingLibelle = "ProduitGroupeReportingLibelle",
  ProduitGroupeReportingCouleur = "ProduitGroupeReportingCouleur",
  ProduitGroupeReportingTypeLibelle = "ProduitGroupeReportingTypeLibelle",
  PUHTUnique = "PUHTUnique",
  RegionEELibelle = "RegionEELibelle",
  RegionReportingLibelle = "RegionReportingLibelle",
  RepreneurContrat = "RepreneurContrat",
  RepreneurLibelle = "RepreneurLibelle",
  RepriseTypeLibelle = "RepriseTypeLibelle",
  RessourceLibelleFRFR = "RessourceLibelleFRFR",
  RessourceLibelleENGB = "RessourceLibelleENGB",
  SAGECategorieAchatLibelle = "SAGECategorieAchatLibelle",
  SAGECategorieVenteLibelle ="SAGECategorieVenteLibelle",
  SAGECodeTransportCode = "SAGECodeTransportCode",
  SAGECodeTransportLibelle = "SAGECodeTransportLibelle",
  SAGEConditionLivraisonLibelle = "SAGEConditionLivraisonLibelle",
  SAGENumeroPiece = "SAGENumeroPiece",
  SAGEDatePiece = "SAGEDatePiece",
  SAGEPeriodiciteLibelle = "SAGEPeriodiciteLibelle",
  SAGEModeReglementLibelle = "SAGEModeReglementLibelle",
  SAGEEntiteCodeTVA = "SAGEEntiteCodeTVA",
  SAGEEntiteIdNational = "SAGEEntiteIdNational",
  ServiceLibelle = "ServiceLibelle",
  StandardLibelle = "StandardLibelle",
  TicketLibelle = "TicketLibelle",
  TicketTexte = "TicketTexte",
  TitreLibelle = "TitreLibelle",
  TransporteurListeCamionTypes = "TransporteurListeCamionTypes",
  UtilisateurActif = "UtilisateurActif",
  UtilisateurNom = "UtilisateurNom",
  UtilisateurLogin = "UtilisateurLogin",
  UtilisateurHabilitationLogistique = "UtilisateurHabilitationLogistique",
  UtilisateurHabilitationAnnuaire = "UtilisateurHabilitationAnnuaire",
  UtilisateurHabilitationMessagerie = "UtilisateurHabilitationMessagerie",
  UtilisateurHabilitationAdministration = "UtilisateurHabilitationAdministration",
  UtilisateurHabilitationQualite = "UtilisateurHabilitationQualite",
  UtilisateurClient = "UtilisateurClient",
  UtilisateurHabilitationModuleTransporteur = "UtilisateurHabilitationModuleTransporteur",
  UtilisateurTransporteur = "UtilisateurTransporteur",
  UtilisateurType = "UtilisateurType",
  UtilisateurHabilitationModuleCollectivite = "UtilisateurHabilitationModuleCollectivite",
  UtilisateurCollectivite = "UtilisateurCollectivite",
  UtilisateurCentreDeTri = "UtilisateurCentreDeTri",
  UtilisateurHabilitationModulePrestataire = "UtilisateurHabilitationModulePrestataire",
  UtilisateurPrestataire = "UtilisateurPrestataire",
  Couleur = "Couleur",
  Mois = "Mois",
  MoisNb = "MoisNb",
  MoisAnnee = "MoisAnnee",
  TrimestreNb = "TrimestreNb",
  Ordre = "Ordre",
  TonnageTotalChargement = "TonnageTotalChargement",
  TonnageTotalDeclare = "TonnageTotalDeclare",
  TonnageMoyen = "TonnageMoyen",
  NbTotalCamion = "NbTotalCamion",
  TonnageSoumisInteressement = "TonnageSoumisInteressement",
  NbLotSoumisInteressement = "NbLotSoumisInteressement",
  NbLotNonConforme = "NbLotNonConforme",
  TauxNonConformite = "TauxNonConformite",
  MontantInteressement = "MontantInteressement",
  SousContratIncitationQualite = "SousContratIncitationQualite",
  MiseEnPlaceAutocontrole = "MiseEnPlaceAutocontrole",
  TonnageSousContrat = "TonnageSousContrat",
  NbAffretement = "NbAffretement",
  NbAffretementPourcentage = "NbAffretementPourcentage",
  NbCommandeFournisseur = "NbCommandeFournisseur",
  CA = "CA",
  CAPourcentage = "CAPourcentage",
  PoidsDechargementTotal = "PoidsDechargementTotal",
  PoidsDechargementAffretement = "PoidsDechargementAffretement",
  KmAffretement = "KmAffretement",
  KmTotal = "KmTotal",
  PrixEuroHT = "PrixEuroHT",
  PrixEuroHTTonne = "PrixEuroHTTonne",
  PrixAchatEuroHT = "PrixAchatEuroHT",
  PrixNetEuroHTTonne = "PrixNetEuroHTTonne",
  MontantEuroHT = "MontantEuroHT",
  MontantEuroHTTonne = "MontantEuroHTTonne",
  PrixTotalTransport = "PrixTotalTransport",
  PrixTransportAffretement = "PrixTransportAffretement",
  PoidsKg = "PoidsKg",
  PoidsTonne = "PoidsTonne",
  PoidsCommande = "PoidsCommande",
  PoidsChargementAttribue = "PoidsChargementAttribue",
  PoidsAttribuePourcentage = "PoidsAttribuePourcentage",
  PoidsRestantALivrer = "PoidsRestantALivrer",
  PoidsChargementDate = "PoidsChargementDate",
  PoidsChargementDatePourcentage = "PoidsChargementDatePourcentage",
  PoidsStockCentreDeTri = "PoidsStockCentreDeTri",
  PoidsStockCentreDeTriPourcentage = "PoidsStockCentreDeTriPourcentage",
  PoidsDechargementReceptionne = "PoidsDechargementReceptionne",
  PoidsDechargementReceptionnePourcentage = "PoidsDechargementReceptionnePourcentage",
  PoidsDontDispoMoisPrecedent = "PoidsDontDispoMoisPrecedent",
  PoidsChargementTonne = "PoidsChargementTonne",
  PoidsDechargementTonne = "PoidsDechargementTonne",
  PoidsDeclareTonne = "PoidsDeclareTonne",
  TonnageAnnuel = "TonnageAnnuel",
  TonnageAnnuelPrecedent = "TonnageAnnuelPrecedent",
  Collecte = "Collecte",
  IncitationQualite = "IncitationQualite",
  ListeComposant = "ListeComposant",
  ListeProduitStandard = "ListeProduitStandard",
  Id = "Id",
  RefAction = "RefAction",
  RefActionType = "RefActionType",
  RefAdresse = "RefAdresse",
  RefAdresseOrigine = "RefAdresseOrigine",
  RefAdresseDestination = "RefAdresseDestination",
  RefAdresseType = "RefAdresseType",
  RefAide = "RefAide",
  RefApplication = "RefApplication",
  RefApplicationProduitOrigine = "RefApplicationProduitOrigine",
  RefCamionType = "RefCamionType",
  RefClientApplication = "RefClientApplication",
  RefCommandeClient = "RefCommandeClient",
  RefCommandeClientMensuelle = "RefCommandeClientMensuelle",
  RefCommandeFournisseur = "RefCommandeFournisseur",
  RefCommandeFournisseurStatut = "RefCommandeFournisseurStatut",
  RefContrat = "RefContrat",
  RefDescriptionControle = "RefDescriptionControle",
  RefDescriptionCVQ = "RefDescriptionCVQ",
  RefDescriptionReception = "RefDescriptionReception",
  RefDocument = "RefDocument",
  RefEcoOrganisme = "RefEcoOrganisme",
  RefEntite = "RefEntite",
  RefEntiteType = "RefEntiteType",
  RefEquipementier = "RefEquipementier",
  RefEquivalentCO2 ="RefEquivalentCO2",
  RefFicheControle = "RefFicheControle",
  RefFonction = "RefFonction",
  RefFormeContact = "RefFormeContact",
  RefFournisseurTO = "RefFournisseurTO",
  RefJourFerie = "RefJourFerie",
  RefMessage = "RefMessage",
  RefMessageType = "RefMessageType",
  RefModeTransportEE = "RefModeTransportEE",
  RefMontantIncitationQualite = "RefMontantIncitationQualite",
  RefMotifAnomalieChargement = "RefMotifAnomalieChargement",
  RefMotifAnomalieClient = "RefMotifAnomalieClient",
  RefMotifAnomalieTransporteur = "RefMotifAnomalieTransporteur",
  RefMotifCamionIncomplet = "RefMotifCamionIncomplet",
  RefNonConformite = "RefNonConformite",
  RefNonConformiteDemandeClientType = "RefNonConformiteDemandeClientType",
  RefNonConformiteEtapeType = "RefNonConformiteEtapeType",
  RefNonConformiteFamille = "RefNonConformiteFamille",
  RefNonConformiteNature = "RefNonConformiteNature",
  RefNonConformiteReponseClientType = "RefNonConformiteReponseClientType",
  RefNonConformiteReponseFournisseurType = "RefNonConformiteReponseFournisseurType",
  RefParamEmail = "RefParamEmail",
  RefParametre = "RefParametre",
  RefPrixReprise = "RefPrixReprise",
  RefProcess = "RefProcess",
  RefProduit = "RefProduit",
  RefProduitGroupeReportingType = "RefProduitGroupeReportingType",
  RefProduitGroupeReporting = "RefProduitGroupeReporting",
  RefRegionEE = "RefRegionEE",
  RefRegionReporting = "RefRegionReporting",
  RefRepartition = "RefRepartition",
  RefRepreneur = "RefRepreneur",
  RefRepriseType = "RefRepriseType",
  RefRessource = "RefRessource",
  RefSAGECodeTransport = "RefSAGECodeTransport",
  RefService = "RefService",
  RefSurcoutCarburant = "RefSurcoutCarburant",
  RefTicket = "RefTicket",
  RefTitre = "RefTitre",
  RefTransport = "RefTransport",
  RefTransporteur = "RefTransporteur",
  RepartitionD = "RepartitionD",
  SurcoutCarburantRatio = "SurcoutCarburantRatio",
  TransporteurLibelle = "TransporteurLibelle",
  TransportPrix = "TransportPrix",
  TransportPUHT = "TransportPUHT",
  TransportPUHTDemande = "TransportPUHTDemande",
  TransportTotalPrix = "TransportTotalPrix",
  GenerePar = "GenerePar",
  Janvier = "Janvier",
  Fevrier = "Fevrier",
  Mars = "Mars",
  Avril = "Avril",
  Mai = "Mai",
  Juin = "Juin",
  Juillet = "Juillet",
  Aout = "Aout",
  Septembre = "Septembre",
  Octobre = "Octobre",
  Novembre = "Novembre",
  Decembre = "Decembre",
  JanvierKg = "JanvierKg",
  FevrierKg = "FevrierKg",
  MarsKg = "MarsKg",
  AvrilKg = "AvrilKg",
  MaiKg = "MaiKg",
  JuinKg = "JuinKg",
  JuilletKg = "JuilletKg",
  AoutKg = "AoutKg",
  SeptembreKg = "SeptembreKg",
  OctobreKg = "OctobreKg",
  NovembreKg = "NovembreKg",
  DecembreKg = "DecembreKg",
  JanvierRegionPercent = "JanvierRegionPercent",
  FevrierRegionPercent = "FevrierRegionPercent",
  MarsRegionPercent = "MarsRegionPercent",
  AvrilRegionPercent = "AvrilRegionPercent",
  MaiRegionPercent = "MaiRegionPercent",
  JuinRegionPercent = "JuinRegionPercent",
  JuilletRegionPercent = "JuilletRegionPercent",
  AoutRegionPercent = "AoutRegionPercent",
  SeptembreRegionPercent = "SeptembreRegionPercent",
  OctobreRegionPercent = "OctobreRegionPercent",
  NovembreRegionPercent = "NovembreRegionPercent",
  DecembreRegionPercent = "DecembreRegionPercent",
  AnnuelPrecedentRegionPercent = "AnnuelPrecedentRegionPercent",
  AnnuelRegionPercent = "AnnuelRegionPercent"
}

//Enumération pour les process de contact adresse
export enum ContactAdresseProcess {
  "BonDeLivraison" = 1,
  "DemandeEnlevement" = 2,
  "EtatTrimestriel" = 3,
  "FicheRepartition" = 4,
  "InteressementCentreDeTri" = 5,
  "RepriseCollectivite" = 6,
  "ReceptionMensuelle" = 7,
  "IncitationQualite" = 8,
  "ControleurQualite" = 9,
}

//Enumération for CommandeFournisseurStatut
export enum CommandeFournisseurStatut {
  "Ouverte" = 1,
  "EnAttente" = 2,
  "Bloquee" = 3,
}

//Enumération for CommandeFournisseurStatut
export enum EnvCommandeFournisseurStatutName {
  Repartie = "Repartie",
  Receptionnee = "Receptionnee",
  Ouverte = "Ouverte",
  EnAttente = "EnAttente",
  Bloquee = "Bloquee",
  DemandeEnlevement = "DemandeEnlevement",
  Refusee = "Refusee"
}

//NonConformite file type
export enum NonConformiteFichierType {
  "Client" = 1,
  "Fournisseur" = 2,
  "FacturationFournisseur" = 3,
  "Cloture" = 4
}

//Data types
export enum DataType {
  decimalNumber2 = "decimalNumber2",
  decimalNumber3 = "decimalNumber3",
  date = "date",
  dateTime = "dateTime",
  month = "month",
  monthNumber = "monthNumber",
  monthYear = "monthYear",
  quarterNumber = "quarterNumber",
  yearNumber = "yearNumber",
  bit = "bit",
  id = "id",
  intNumber = "intNumber",
  numeroCommande = "numeroCommande",
  text = "text",
  year = "year",
  percent = "percent"
}

//Imput form element type
export enum InputFormComponentElementType {
  NonConformiteCmt = "NonConformiteCmt",
  LoginEmailLost = "LoginEmailLost",
  NoEmail = "NoEmail"
}

//Search element type
export enum SearchElementType {
  Entite = "Entite",
  ContactAdresse = "ContactAdresse",
  CommandeFournisseur = "CommandeFournisseur"
}

//Search result type
export enum SearchResultType {
  CDT = "CDT",
  Client = "Client",
  Collectivite = "Collectivite",
  Transporteur = "Transporteur"
}

// Form control types
export enum FormControlType {
  Texte = "Texte",
  TexteMulti = "TexteMulti",
  Checkbox = "Checkbox",
  DatePicker = "DatePicker",
  List = "List",
}

export enum ListContentType {
  Pays = "Pays",
  RegionReportingRef = "RegionReportingRef",
  ProduitGroupeReportingTypeRef = "ProduitGroupeReportingTypeRef",
  Couleur = "Couleur",
  ModeTransportEE = "ModeTransportEE"
}
//Document types for Module Collectivité
export enum DocumentType {
  NoteCredit = "NoteCredit",
  EtatTrimestrielCS = "EtatTrimestrielCS",
  EtatMensuelHCS = "EtatMensuelHCS",
  CertificatRecyclageCS = "CertificatRecyclageCS",
  CertificatRecyclageHCS = "CertificatRecyclageHCS",
  Documents = "Documents",
  EtatMensuelReception = "EtatMensuelReception",
  Parametre = "Parametre"
}

//Enumération pour les types de statistiques
export enum StatType {
  DonneeCDT = "DonneeCDT",
  ExtractionRSE = "ExtractionRSE",
  ExtractionPrixReprise = "ExtractionPrixReprise",
  DestinationTonnage = "DestinationTonnage",
  DestinationTonnageParPays = "DestinationTonnageParPays",
  DeboucheBalle = "DeboucheBalle",
  EvolutionTonnage = "EvolutionTonnage"
}

//Enumération pour les types d'utilisateurs
export enum UtilisateurType {
  Valorplast = "Valorplast",
  Collectivite = "Collectivite",
  Transporteur = "Transporteur",
  Client = "Client",
  CentreDeTri = "CentreDeTri",
  Prestataire = "Prestataire"
}
//Enumération pour les types de contrats
export enum ContratType {
  "RepriseIndividuelle" = 1,
}
