/// <Propriété>
/// -----------------------------------------------------------------------------------------------------
/// Société Enviromatic sarl (Copyright)
/// 11 rue du Hainaut
/// 78570 Andrésy
/// -----------------------------------------------------------------------------------------------------
/// Projet : e-Valorplast
/// Création : 01/01/2019
/// ----------------------------------------------------------------------------------------------------- 

namespace eVaSys.Utils
{
    public class Enumerations
    {
        //Enumération pour les types de donnée des colonnes
        public enum EnvDataColumnDataType
        {
            decimalNumber2,
            decimalNumber3,
            date,
            dateTime,
            month,
            monthNumber,
            monthYear,
            quarterNumber,
            yearNumber,
            bit,
            id,
            intNumber,
            numeroCommande,
            text,
            year,
            percent
        }
        //Enumération pour les process de contact adresse
        public enum ContactAdresseProcess
        {
            BonDeLivraison = 1,
            DemandeEnlevement = 2,
            EtatTrimestrielCollectivites = 3,
            FicheDeRepartition = 4,
            InteressementCentreDeTri = 5,
            RepriseCollectivite = 6,
            ReceptionMensuelle = 7,
            IncitationQualite = 8,
            ControleurQualite = 9,
        }
        //Enumération pour les statuts de comandes fournisseur
        public enum CommandeFournisseurStatut
        {
            Ouvert = 1,
            EnAttente = 2,
            Bloque = 3,
        }
        //Enumération pour les process
        public enum Process
        {
            Classique = 2,
            Pilote = 3,
            TSR = 4,
        }
        //NonConformite file type
        public enum NonConformiteFichierType
        {
            Client = 1,
            Fournisseur = 2,
            FacturationFournisseur = 3,
            Cloture = 4
        }
        //Enumération pour les données verrouillables
        public enum DataTypeToLock
        {
            RefCommandeFournisseur,
            RefMontantIncitationQualite
        }
        //Enumération pour les droits
        public enum ObjectRight
        {
            R, W, D
        }
        //Enumération pour les modules
        public enum Module
        {
            Administration, Annuaire, Logistique, Statistique, Messagerie, Qualite, ModuleCollectivite, ModulePrestataire
        }
        //Enumération pour les habilitations Module administration
        public enum HabilitationAdministration
        {
            Administrateur
        }
        //Enumération pour les habilitationsqualité
        public enum HabilitationQualite
        {
            Administrateur, Utilisateur, Client, Fournisseur
        }
        //Enumération pour les habilitations Module logistique
        public enum HabilitationLogistique
        {
            Administrateur, Transporteur, Client, Utilisateur, CentreDeTri
        }
        //Enumération pour les habilitations module collectivité
        public enum HabilitationModuleCollectivite
        {
            Administrateur, Utilisateur
        }
        //Enumération pour les habilitations Module centre de tri
        public enum HabilitationModuleCentreDeTri
        {
            Administrateur, Utilisateur
        }
        //Messagerie module habilitation
        public enum HabilitationMessagerie
        {
            Administrateur, Utilisateur
        }
        //Enumération pour les habilitations de l'annuaire
        public enum HabilitationAnnuaire
        {
            Administrateur, Visualisation, Utilisateur
        }
        //Enumération pour les habilitations Module Prestataire
        public enum HabilitationModulePrestataire
        {
            Administrateur, Transporteur, Client, Fournisseur
        }
        //Enumération pour les noms de modules
        public enum ModuleName
        {
            Administration,
            Annuaire,
            Logistique,
            Statistique,
            Messagerie,
            Qualite,
            ModuleCollectivite,
            ModuleCentreDeTri,
            ModulePrestataire
        }
        //Enumération pour les noms de menus
        public enum MenuName
        {
            AdministrationMenuActionType,
            AdministrationMenuAdresseType,
            AdministrationMenuAide,
            AdministrationMenuApplication,
            AdministrationMenuApplicationProduitOrigine,
            AdministrationMenuCamionType,
            AdministrationMenuCivilite,
            AdministrationMenuClientApplication,
            AdministrationMenuDescriptionControle,
            AdministrationMenuDescriptionCVQ,
            AdministrationMenuDescriptionReception,
            AdministrationMenuDocument,
            AdministrationMenuEntiteType,
            AdministrationMenuEquipementier,
            AdministrationMenuEcoOrganisme,
            AdministrationMenuEquivalentCO2,
            AdministrationMenuExtractionLogin,
            AdministrationMenuFonction,
            AdministrationMenuFormeContact,
            AdministrationMenuFournisseurTO,
            AdministrationMenuJourFerie,
            AdministrationMenuMessageType,
            AdministrationMenuModeTransportEE,
            AdministrationMenuMontantIncitationQualite,
            AdministrationMenuMotifAnomalieChargement,
            AdministrationMenuMotifAnomalieClient,
            AdministrationMenuMotifAnomalieTransporteur,
            AdministrationMenuMotifCamionIncomplet,
            AdministrationMenuNonConformiteDemandeClientType,
            AdministrationMenuNonConformiteFamille,
            AdministrationMenuNonConformiteNature,
            AdministrationMenuNonConformiteReponseClientType,
            AdministrationMenuNonConformiteReponseFournisseurType,
            AdministrationMenuParamEmail,
            AdministrationMenuParametre,
            AdministrationMenuPays,
            AdministrationMenuProcess,
            AdministrationMenuProduit,
            AdministrationMenuProduitGroupeReportingType,
            AdministrationMenuProduitGroupeReporting,
            AdministrationMenuRegionEE,
            AdministrationMenuRegionReporting,
            AdministrationMenuRepreneur,
            AdministrationMenuRepriseType,
            AdministrationMenuRessource,
            AdministrationMenuSAGECodeTransport,
            AdministrationMenuSecurite,
            AdministrationMenuService,
            AdministrationMenuSuiviLogin,
            AdministrationMenuStandard,
            AdministrationMenuTicket,
            AdministrationMenuUtilisateur,
            AdministrationMenuTitre,
            AdministrationMenuUtilisateurInactif,
            AnnuaireMenuNbAffretementTransporteur,
            AnnuaireMenuIncitationQualite,
            AnnuaireMenuEmailNoteCreditCollectivite,
            AnnuaireMenuSuiviEnvois,
            AnnuaireMenuEntite,
            AnnuaireMenuExtractionAction,
            AnnuaireMenuExtractionAnnuaire,
            LogistiqueMenuChargementAnnule,
            LogistiqueMenuCommandeClient,
            LogistiqueMenuCommandeFournisseur,
            LogistiqueMenuEtatReception,
            LogistiqueMenuEtatCoutTransport,
            LogistiqueMenuExportSAGE,
            LogistiqueMenuExtractionTransport,
            LogistiqueMenuImporterTransport,
            LogistiqueMenuImpression,
            LogistiqueMenuLotDisponible,
            LogistiqueMenuModifierTransport,
            LogistiqueMenuPrixReprise,
            LogistiqueMenuRepartition,
            LogistiqueMenuSupprimerTransportEnMasse,
            LogistiqueMenuTransportCommande,
            LogistiqueMenuTransportCommandeEnCours,
            LogistiqueMenuTransportCommandeModifiee,
            LogistiqueMenuTransportDemandeEnlevement,
            LogistiqueMenuModifierTousPrixTransport,
            LogistiqueMenuTransportNonValide,
            LogistiqueMenuValiderNouveauPrixTransport,
            LogistiqueMenuSurcoutCarburant,
            LogistiqueMenuEtatReceptionEmballagePlastique,
            LogistiqueMenuEtatSuiviTonnageRecycleur,
            LogistiqueMenuEtatDesFluxDev,
            LogistiqueMenuEtatDesFluxDevLeko,
            LogistiqueMenuEtatTarifTransporteurClient,
            LogistiqueMenuExtractionLeko,
            LogistiqueMenuPartMarcheTransporteur,
            LogistiqueMenuEtatKmMoyen,
            LogistiqueMenuSuiviCommandeClient,
            LogistiqueMenuSuiviCommandeClientProduit,
            LogistiqueMenuDelaiCommandeEnlevement,
            LogistiqueMenuEtatReceptionProduit,
            LogistiqueMenuEtatReceptionProduitDR,
            LogistiqueMenuExtractionReception,
            LogistiqueMenuEtatReceptionFournisseurChargement,
            LogistiqueMenuExtractionCommande,
            LogistiqueMenuEtatDesPoids,
            LogistiqueMenuEtatTonnageParProcess,
            LogistiqueMenuEtatVenteAnnuelleProduitClient,
            LogistiqueMenuEtatDestinationAnnuelleProduitClient,
            LogistiqueMenuSuiviFacturationHC,
            LogistiqueMenuTonnageCollectiviteProduit,
            LogistiqueMenuTonnageCDTProduitComposant,
            LogistiqueMenuTonnageCLSousContrat,
            LogistiqueMenuListeProduit,
            LogistiqueMenuEtatDesEnlevements,
            LogistiqueMenuPoidsMoyenChargementProduit,
            MenuVisualisationAnnuaire,
            MenuDocuments,
            MessagerieMenuMessage,
            MessagerieMenuVisualisation,
            ModuleCollectiviteMenuAccueil,
            ModuleCollectiviteMenuDocuments,
            ModuleCollectiviteMenuPrixReprise,
            ModuleCollectiviteMenuStatistiques,
            ModuleCollectiviteMenuVisualisationAnnuaire,
            ModulePrestataireMenuCommandeFournisseur,
            QualiteMenuControle,
            QualiteMenuNonConformite,
            QualiteMenuRepartitionControleClient,
            QualiteMenuExtractionFicheControle,
            QualiteMenuExtractionControle,
            QualiteMenuExtractionNonConformite,
            QualiteMenuExtractionCVQ,
            QualiteMenuEtatIncitationQualite,
            QualiteMenuEtatControleReception,
            AnnuaireMenuEvolutionTonnage
        }
        //Enumération pour les noms de CommandeFournisseur statuts
        public enum CommandeFournisseurStatutName
        {
            Repartie,
            Receptionnee,
            Ouverte,
            EnAttente,
            Bloquee,
            DemandeEnlevement,
            Refusee
        }
        //Enumération pour les types de statistiques
        public enum StatType
        {
            DonneeCDT,
            ExtractionRSE,
            ExtractionPrixReprise,
            DestinationTonnage,
            DestinationTonnageParPays,
            DeboucheBalle,
            EvolutionTonnage
        }
        //Enumération pour les noms des actions
        public enum ActionName
        {
            IncitationQualite,
            EmailNoteCreditCollectivite,
            ValidateTransportPrice,
            RejectTransportPrice,
            DeleteTransport,
            SetEnAttente,
            ChangeMoisDechargementPrevu,
            Mixte,
            CopyPrixReprise,
            TransporteurForUtilisateur,
            CentreDeTriForUtilisateur,
            CollectiviteForUtilisateur,
            ClientForUtilisateur,
            PrestataireForUtilisateur,
            UtilisateurMaitreForUtilisateur,
            EntiteForDocument,
            Search,
            DeactivateUtilisateur,
            ContactModificationRequest
        }
        //Enumération pour les noms de colonne
        public enum  DataColumnName
        {
            ActionCmt,
            ActionDate,
            ActionLibelle,
            ActionTypeDocumentType,
            ActionTypeLibelle,
            Adresse,
            AdresseActif,
            AdresseLibelle,
            AdresseAdr1,
            AdresseAdr2,
            AdresseCodePostal,
            AdresseVille,
            AdresseTel,
            AdresseEmail,
            AdresseHoraires,
            AdresseSiteWeb,
            TexteContactAdresseList,
            TexteAdresseList,
            AdresseDestinationCP,
            AdresseDestinationDpt,
            AdresseDestinationTypeLibelle,
            AdresseDestinationVille,
            AdresseOrigineCP,
            AdresseOrigineTypeLibelle,
            AdresseOrigineVille,
            AdresseTypeLibelle,
            AideComposant,
            AideValeurHTML,
            AideLibelleFRFR,
            AideLibelleENGB,
            ApplicationLibelle,
            ApplicationProduitOrigineLibelle,
            Annee,
            AnneeNb,
            AnneeTexte,
            CamionTypeLibelle,
            CentreDeTriLibelle,
            CentreDeTriListeCamionTypes,
            CiviliteLibelle,
            ClientLibelle,
            CommandeClientMensuelleD,
            CommandeClientMensuellePoids,
            CommandeClientPositionne,
            CommandeFournisseurAdresseOrigineDpt,
            CommandeFournisseurAdresseOrigineVille,
            CommandeFournisseurCamionComplet,
            CommandeFournisseurCamionCompletInvisible,
            CommandeFournisseurCB,
            CommandeFournisseurChargementAnnulePar,
            CommandeFournisseurChargementEffectue,
            CommandeFournisseurCmtAnomalieChargement,
            CommandeFournisseurCmtAnomalieTransporteur,
            CommandeFournisseurCmtAnomalieClient,
            CommandeFournisseurCmtChargementAnnule,
            CommandeFournisseurCmtFournisseur,
            CommandeFournisseurCVQ,
            CommandeFournisseurDAffretement,
            CommandeFournisseurDAnomalieChargement,
            CommandeFournisseurDAnomalieTransporteur,
            CommandeFournisseurDAnomalieClient,
            CommandeFournisseurDateCreation,
            CommandeFournisseurDChargement,
            CommandeFournisseurDChargementAnnule,
            CommandeFournisseurDChargementPrevue,
            CommandeFournisseurDDechargement,
            CommandeFournisseurDDechargementInvisible,
            CommandeFournisseurDDechargementPrevue,
            CommandeFournisseurDelaiChargement,
            CommandeFournisseurDelaiCommande,
            CommandeFournisseurDDisponibilite,
            CommandeFournisseurDTraitementAnomalieChargementInvisible,
            CommandeFournisseurDTraitementAnomalieClientInvisible,
            CommandeFournisseurDTraitementAnomalieTransporteurInvisible,
            CommandeFournisseurDTraitementAnomalieChargement,
            CommandeFournisseurDTraitementAnomalieClient,
            CommandeFournisseurDTraitementAnomalieTransporteur,
            CommandeFournisseurFicheControle,
            CommandeFournisseurHoraireDechargementPrevu,
            CommandeFournisseurImprime,
            CommandeFournisseurKm,
            CommandeFournisseurLimiteExclusivite,
            CommandeFournisseurLotControle,
            CommandeFournisseurMixte,
            CommandeFournisseurMoisDechargementPrevu,
            CommandeFournisseurNbBalleChargement,
            CommandeFournisseurNbBalleDechargement,
            CommandeFournisseurNumeroAffretement,
            CommandeFournisseurNumeroCommande,
            CommandeFournisseurPoidsChargement,
            CommandeFournisseurPoidsDechargement,
            CommandeFournisseurPoidsReparti,
            CommandeFournisseurStatut,
            CommandeFournisseurPrixTonneHT,
            CommandeFournisseurPrixTransportHT,
            CommandeFournisseurPrixTransportSupplementHT,
            CommandeFournisseurRefExt,
            CommandeFournisseurSurcoutCarburantHT,
            CommandeFournisseurNonConformite,
            CommandeFournisseurNonConformiteInvisible,
            CommandeFournisseurNbTotalLivraison,
            CommandeFournisseurNbTotalLivraisonAControler,
            CommandeFournisseurNbTotalLivraisonControlees,
            CommandeFournisseurTauxControle,
            ComposantLibelle,
            Connexions,
            CollectiviteLibelle,
            ContactAdresseActif,
            ContactAdresseCmt,
            ContactAdresseCmtServiceFonction,
            ContactAdresseEmail,
            ContactAdresseIsUser,
            ContactAdresseListeFonctionServices,
            ContactAdresseListeProcesss,
            ContactAdresseTel,
            ContactAdresseTelMobile,
            ContactPrenom,
            ContactNom,
            ContratCollectiviteDebut,
            ContratCollectiviteFin,
            ContratIncitationQualiteDebut,
            ContratIncitationQualiteFin,
            ControleCmt,
            ControleDControle,
            ControlePoids,
            ControlePoidsTotal,
            ControlePoidsTotalIndesirable,
            ControlePourcentageIndesirable,
            Controles,
            CreationPar,
            CVQCmt,
            CVQDCVQ,
            D,
            DescriptionControleActif,
            DescriptionControleCalculLimiteConformite,
            DescriptionControleLibelleFRFR,
            DescriptionControleLibelleENGB,
            DescriptionControleOrdre,
            DescriptionCVQActif,
            DescriptionCVQLibelleFRFR,
            DescriptionCVQLibelleENGB,
            DescriptionCVQLimiteBasse,
            DescriptionCVQLimiteHaute,
            DescriptionCVQOrdre,
            DescriptionReceptionActif,
            DescriptionReceptionLibelleFRFR,
            DescriptionReceptionLibelleENGB,
            DescriptionReceptionOuiFRFR,
            DescriptionReceptionOuiENGB,
            DescriptionReceptionNonFRFR,
            DescriptionReceptionNonENGB,
            DescriptionReceptionOrdre,
            DocumentActif,
            DocumentDescription,
            DocumentLibelle,
            DocumentJoint,
            DLogin,
            DLogout,
            DRActif,
            EconomieCO2KgT,
            EcoOrganismeLibelle,
            EmailDEnvoi,
            EntiteActionnaireProprietaire,
            EntiteAssujettiTVA,
            EntiteCapacite,
            EntiteContratCollectiviteActif,
            EntiteDimensionBalle,
            EntiteCodeCITEO,
            EntiteCodeTVA,
            EntiteCodeValorisation,
            EntiteCmt,
            EntiteExploitant,
            EntiteExportSAGE,
            EntiteIdNational,
            EntiteLibelle,
            EntiteListe,
            EntiteListeCentreDeTriActifs,
            EntiteListeCentreDeTriInactifs,
            EntiteListeCentreDeTriActifInterdits,
            EntiteListeCollectiviteActifs,
            EntiteListeCollectiviteInactifs,
            EntiteListeContratCollectivites,
            EntiteListeClientActifInterdits,
            EntiteTransporteurActifInterdits,
            EntiteListeDocumentPublic,
            EntiteListeDocumentValorplast,
            EntiteListeIndustrielActifs,
            EntiteListeProcesss,
            EntiteListeProduits,
            EntiteListeProduitInterdits,
            EntiteListeStandards,
            EntitePopulationContratN,
            EntiteReconductionIncitationQualite,
            EntiteRepartitionMensuelle,
            EntiteSousContrat,
            EntiteActif,
            EntiteAdelphe,
            EntiteSAGECodeComptable,
            EntiteSAGECompteTiers,
            EntiteSurcoutCarburant,
            EntiteTypeLibelle,
            EntiteTypeLibelleENGB,
            EntiteTypeLibelleFRFR,
            EntiteTypeListe,
            EntiteVisibiliteAffretementCommun,
            EquipementierLibelle,
            EquivalentCO2Libelle,
            EquivalentCO2Ordre,
            EquivalentCO2Ratio,
            EquivalentCO2Actif,
            FicheControleControle,
            FicheControleCVQ,
            FicheControleReception,
            FicheControleReclamation,
            FicheControleNumeroLotUsine,
            FicheControleReserve,
            FicheControleCmt,
            FicheControleControleur,
            FonctionLibelle,
            FormeContactLibelle,
            FournisseurLibelle,
            FournisseurTOLibelle,
            JourFerie,
            ListeDR,
            MessageLibelle,
            MessageDDebut,
            MessageDFin,
            MessageTitre,
            MessageTypeLibelle,
            MessageVisualisationD,
            MessageVisualisationConfirme,
            MessageVisualisationPar,
            ModeTransportEELibelle,
            ModificationPar,
            Montant,
            MotifAnomalieChargementLibelle,
            MotifAnomalieClientLibelle,
            MotifAnomalieTransporteurLibelle,
            MotifCamionIncompletLibelle,
            Nb,
            NonConformiteDateCreation,
            NonConformiteDescrClient,
            NonConformiteDescrValorplast,
            NonConformiteIF,
            NonConformiteIFClient,
            NonConformiteIFFournisseur,
            NonConformiteIFClientCmtFacturation,
            NonConformiteIFClientDFacture,
            NonConformiteIFClientFactureMontant,
            NonConformiteIFClientFactureNro,
            NonConformiteIFFournisseurAttenteBonCommandeNro,
            NonConformiteIFFournisseurBonCommandeNro,
            NonConformiteIFFournisseurCmtFacturation,
            NonConformiteIFFournisseurDeductionTonnage,
            NonConformiteIFFournisseurFactureMontant,
            NonConformiteIFFournisseurFactureNro,
            NonConformiteIFFournisseurTransmissionFacturation,
            NonConformitePlanAction,
            NonConformitePriseEnCharge,
            NonConformiteMontantPriseEnCharge,
            NonConformitePlanActionNonConcerne,
            NonConformiteIFFournisseurFacture,
            NonConformiteActionDR,
            NonConformiteDTransmissionFournisseur,
            NonConformiteCmtPriseEnCharge,
            NonConformiteCmtReponseFournisseur,
            NonConformiteCmtReponseClient,
            NonConformiteIFFournisseurRetourLot,
            NonConformiteListeFamille,
            NonConformiteOriginePlanActionSaisi,
            NonConformiteEtapeDValide,
            NonConformiteEtapeLibelle,
            NonConformiteCloturee,
            NonConformiteClotureeInvisible,
            NonConformiteDemandeClientTypeActif,
            NonConformiteDemandeClientTypeLibelle,
            NonConformiteDemandeClientTypeLibelleFRFR,
            NonConformiteDemandeClientTypeLibelleENGB,
            NonConformiteAccordFournisseurTypeLibelle,
            NonConformiteFamilleActif,
            NonConformiteFamilleIncitationQualite,
            NonConformiteFamilleLibelle,
            NonConformiteFamilleLibelleFRFR,
            NonConformiteFamilleLibelleENGB,
            NonConformiteNatureActif,
            NonConformiteNatureIncitationQualite,
            NonConformiteNatureLibelle,
            NonConformiteNatureLibelleFRFR,
            NonConformiteNatureLibelleENGB,
            NonConformiteReponseClientTypeActif,
            NonConformiteReponseClientTypeLibelle,
            NonConformiteReponseClientTypeLibelleFRFR,
            NonConformiteReponseClientTypeLibelleENGB,
            NonConformiteReponseFournisseurTypeActif,
            NonConformiteReponseFournisseurTypeLibelle,
            NonConformiteReponseFournisseurTypeLibelleFRFR,
            NonConformiteReponseFournisseurTypeLibelleENGB,
            ParamEmailActif,
            ParamEmailComptePOP,
            ParamEmailEmailExpediteur,
            ParamEmailLibelleExpediteur,
            ParametreLibelle,
            ParametreServeur,
            ParametreValeurNumerique,
            ParametreValeurTexte,
            ParametreValeurHTML,
            ParcoursKm,
            PaysActif,
            PaysDestinbationLibelle,
            PaysCodeISO,
            PaysLibelle,
            Periode,
            PoidsRepartiCITEO,
            PoidsRepartiAdelphe,
            PoidsRepartiLeko,
            Pourcentage,
            PremieresConnexions,
            PrixRepriseD,
            PrixReprisePUHT,
            PrixReprisePUHTSurtri,
            PrixReprisePUHTTransport,
            ProcessLibelle,
            ProduitComposant,
            ProduitLibelle,
            ProduitActif,
            ProduitNomCommercial,
            ProduitNomCommun,
            ProduitNumeroStatistique,
            ProduitCo2KgParT,
            ProduitCodeListeVerte,
            ProduitCodeEE,
            ProduitPUHTSurtri,
            ProduitPUHTTransport,
            ProduitCmt,
            ProduitCmtFournisseur,
            ProduitCmtTransporteur,
            ProduitCmtClient,
            ProduitGroupeReportingLibelle,
            ProduitGroupeReportingCouleur,
            ProduitGroupeReportingTypeLibelle,
            RegionEELibelle,
            RegionReportingLibelle,
            RepreneurLibelle,
            RepreneurContrat,
            RepriseTypeLibelle,
            RessourceLibelleFRFR,
            RessourceLibelleENGB,
            SAGECategorieAchatLibelle,
            SAGECategorieVenteLibelle,
            SAGECodeTransportCode,
            SAGECodeTransportLibelle,
            SAGEConditionLivraisonLibelle,
            SAGENumeroPiece,
            SAGEDatePiece,
            SAGEPeriodiciteLibelle,
            SAGEModeReglementLibelle,
            SAGEEntiteCodeTVA,
            SAGEEntiteIdNational,
            ServiceLibelle,
            StandardLibelle,
            TicketLibelle,
            TicketTexte,
            TitreLibelle,
            TransporteurListeCamionTypes,
            UtilisateurNom,
            UtilisateurActif,
            UtilisateurLogin,
            UtilisateurHabilitationLogistique,
            UtilisateurHabilitationAnnuaire,
            UtilisateurHabilitationMessagerie,
            UtilisateurHabilitationAdministration,
            UtilisateurHabilitationQualite,
            UtilisateurClient,
            UtilisateurHabilitationModuleTransporteur,
            UtilisateurTransporteur,
            UtilisateurType,
            UtilisateurHabilitationModuleCollectivite,
            UtilisateurCollectivite,
            UtilisateurCentreDeTri,
            UtilisateurHabilitationModulePrestataire,
            UtilisateurPrestataire,
            Couleur,
            Mois,
            MoisNb,
            MoisAnnee,
            TrimestreNb,
            Ordre,
            TonnageTotalChargement,
            TonnageTotalDeclare,
            TonnageMoyen,
            NbTotalCamion,
            TonnageSoumisInteressement,
            NbLotSoumisInteressement,
            NbLotNonConforme,
            TauxNonConformite,
            MontantInteressement,
            SousContratIncitationQualite,
            MiseEnPlaceAutocontrole,
            TonnageSousContrat,
            NbAffretement,
            NbAffretementPourcentage,
            NbCommandeFournisseur,
            CA,
            CAPourcentage,
            PoidsDechargementTotal,
            PoidsDechargementAffretement,
            KmAffretement,
            KmTotal,
            PrixEuroHT,
            PrixEuroHTTonne,
            PrixAchatEuroHT,
            PrixNetEuroHTTonne,
            MontantEuroHT,
            MontantEuroHTTonne,
            PrixTotalTransport,
            PrixTransportAffretement,
            PoidsKg,
            PoidsTonne,
            PoidsCommande,
            PoidsChargementAttribue,
            PoidsAttribuePourcentage,
            PoidsRestantALivrer,
            PoidsChargementDate,
            PoidsChargementDatePourcentage,
            PoidsStockCentreDeTri,
            PoidsStockCentreDeTriPourcentage,
            PoidsDechargementReceptionne,
            PoidsDechargementReceptionnePourcentage,
            PoidsDontDispoMoisPrecedent,
            PoidsChargementTonne,
            PoidsDechargementTonne,
            PoidsDeclareTonne,
            TonnageAnnuel,
            TonnageAnnuelPrecedent,
            Collecte,
            IncitationQualite,
            ListeComposant,
            ListeProduitStandard,
            Id,
            RefAction,
            RefActionType,
            RefAdresse,
            RefAdresseOrigine,
            RefAdresseDestination,
            RefAdresseType,
            RefAide,
            RefApplication,
            RefApplicationProduitOrigine,
            RefClientApplication,
            RefCamionType,
            RefCivilite,
            RefCommandeClient,
            RefCommandeClientMensuelle,
            RefCommandeFournisseur,
            RefCommandeFournisseurStatut,
            RefDescriptionControle,
            RefDescriptionCVQ,
            RefDescriptionReception,
            RefDocument, 
            RefEntite,
            RefEntiteType,
            RefEquipementier,
            RefEcoOrganisme,
            RefEquivalentCO2,
            RefFicheControle,
            RefFonction,
            RefFormeContact,
            RefFournisseurTO,
            RefJourFerie,
            RefMessage,
            RefMessageType,
            RefModeTransportEE,
            RefMontantIncitationQualite,
            RefMotifAnomalieChargement,
            RefMotifAnomalieClient,
            RefMotifAnomalieTransporteur,
            RefMotifCamionIncomplet,
            RefNonConformite,
            RefNonConformiteDemandeClientType,
            RefNonConformiteEtapeType,
            RefNonConformiteFamille,
            RefNonConformiteNature,
            RefNonConformiteReponseClientType,
            RefNonConformiteReponseFournisseurType,
            RefParamEmail,
            RefParametre,
            RefPays,
            RefPrixReprise,
            RefProcess,
            RefProduit,
            RefProduitGroupeReportingType,
            RefProduitGroupeReporting,
            RefRegionEE,
            RefRegionReporting,
            RefRepartition,
            RefRepreneur,
            RefRepriseType,
            RefRessource,
            RefSAGECodeTransport,
            RefService,
            RefStandard,
            RefSurcoutCarburant,
            RefTicket,
            RefTitre,
            RefTransport,
            RefTransporteur,
            RefUtilisateur,
            RepartitionD,
            SurcoutCarburantRatio,
            TransporteurLibelle,
            TransportPrix,
            TransportPUHT,
            TransportPUHTDemande,
            TransportTotalPrix,
            GenerePar,
            Janvier,
            Fevrier,
            Mars,
            Avril,
            Mai,
            Juin,
            Juillet,
            Aout,
            Septembre,
            Octobre,
            Novembre,
            Decembre,
            JanvierKg,
            FevrierKg,
            MarsKg,
            AvrilKg,
            MaiKg,
            JuinKg,
            JuilletKg,
            AoutKg,
            SeptembreKg,
            OctobreKg,
            NovembreKg,
            DecembreKg,
            JanvierRegionPercent,
            FevrierRegionPercent,
            MarsRegionPercent,
            AvrilRegionPercent,
            MaiRegionPercent,
            JuinRegionPercent,
            JuilletRegionPercent,
            AoutRegionPercent,
            SeptembreRegionPercent,
            OctobreRegionPercent,
            NovembreRegionPercent,
            DecembreRegionPercent,
            AnnuelPrecedentRegionPercent,
            AnnuelRegionPercent
        }
        //Enumération pour les types de notification
        public enum NotificationAppearance
        {
            info,
            deny,
            warning
        }
        //Enumération pour les objects
        public enum ObjectName
        {
            Action,
            Aide,
            ActionType,
            Adresse,
            AdresseType,
            APICommandeFournisseur,
            Application,
            ClientApplication,
            ApplicationProduitOrigine,
            CamionType,
            Civilite,
            CommandeFournisseur,
            CommandeClient,
            CommandeFournisseurStatut,
            ContactAdresse,
            ContactAdresseProcess,
            ContratType,
            Controle,
            ControleDescriptionControle,
            Couleur,
            CVQ,
            CVQDescriptionCVQ,
            DescriptionControle,
            DescriptionCVQ,
            DescriptionReception,
            Document,
            DocumentEdit,
            Dashboard,
            Dpt,
            Download,
            Email,
            Entite,
            EntiteType,
            Equipementier,
            EcoOrganisme,
            EquivalentCO2,
            ExportSAGE,
            FicheControle,
            FicheControleDescriptionReception,
            Fonction,
            FormeContact,
            FournisseurTO,
            Grid,
            GridSimple,
            JourFerie,
            Message,
            MessageType,
            ModeTransportEE,
            MontantIncitationQualite,
            MotifCamionIncomplet,
            MotifAnomalieChargement,
            MotifAnomalieTransporteur,
            MotifAnomalieClient,
            NonConformite,
            NonConformiteAccordFournisseurType,
            NonConformiteDemandeClientType,
            NonConformiteEtapeType,
            NonConformiteFamille,
            NonConformiteNature,
            NonConformiteReponseClientType,
            NonConformiteReponseFournisseurType,
            ParamEmail,
            Parametre,
            Pays,
            PrixReprise,
            Process,
            Produit,
            ProduitGroupeReporting,
            ProduitGroupeReportingType,
            Reclamation,
            RegionEE,
            RegionReporting,
            Repartition,
            RepriseType,
            Repreneur,
            Ressource,
            SAGECodeTransport,
            Search,
            Securite,
            Service,
            Statistique,
            Standard,
            SurcoutCarburant,
            Titre,
            Ticket,
            Transport,
            Upload,
            Utilisateur,
            Utils
        }

        //Enum for data to lock
        public enum LockableData
        {
            RefCommandeFournisseur
        }

        //Enum Search element type
        public enum SearchElementType
        {
            Entite,
            ContactAdresse,
            CommandeFournisseur
        }

        //Enum Search element type
        public enum SearchResultType
        {
            CDT,
            Client,
            Collectivite,
            Transporteur
        }

        //Enum for APICommandeFournisseur ActionCode values
        public enum APICommandeFournisseurActionCode
        {
            Creation,
            Modification,
            Annulation,
            RefusDocumentationTransporteur,
            RefusDocumentationRecycleur
        }
        //Document types for Module Collectivité
        public enum DocumentType
        {
            NoteCredit,
            EtatTrimestrielCS,
            EtatMensuelHCS,
            CertificatRecyclageCS,
            CertificatRecyclageHCS,
            Documents,
            Parametre
        }
        //Enum for user types
        public enum UtilisateurType
        {
            Valorplast,
            Collectivite,
            Transporteur,
            Client,
            CentreDeTri,
            Prestataire
        }
        //Enum for component names
        public enum ComponentName
        {
            Entite,
            Produit,
        }
        //Enum for ContratType
        public enum ContratType
        {
            RepriseIndividuelle = 1,
        }
    }
}
